const express=require('express');
var english=[
  { "id": "1", "question": "What is the synonym of 'happy'?", "options": ["Joyful", "Sad", "Angry", "Upset"] },
  { "id": "2", "question": "Choose the correctly spelled word.", "options": ["Accommodate", "Acommodate", "Accomodate", "Accomadate"] },
  { "id": "3", "question": "What is the antonym of 'difficult'?", "options": ["Easy", "Hard", "Complicated", "Tough"] },
  { "id": "4", "question": "Choose the correct past tense of 'go'.", "options": ["Goes", "Gone", "Went", "Going"] },
  { "id": "5", "question": "What is the meaning of 'benevolent'?", "options": ["Kind", "Selfish", "Angry", "Rude"] },
  { "id": "6", "question": "Which of the following sentences is correct?", "options": ["He go to school.", "He goes to school.", "He gone to school.", "He going to school."] },
  { "id": "7", "question": "What does the word 'meticulous' mean?", "options": ["Careless", "Careful", "Hasty", "Quick"] },
  { "id": "8", "question": "What is the synonym of 'difficult'?", "options": ["Challenging", "Easy", "Simple", "Light"] },
  { "id": "9", "question": "Which word is opposite to 'noisy'?", "options": ["Loud", "Quiet", "Rowdy", "Chirpy"] },
  { "id": "10", "question": "What is the meaning of 'intricate'?", "options": ["Simple", "Complex", "Easy", "Straightforward"] },
  { "id": "11", "question": "Choose the correct form of the verb: 'She ____ to the store yesterday.'", "options": ["go", "went", "gone", "going"] },
  { "id": "12", "question": "What is the synonym of 'brave'?", "options": ["Courageous", "Fearful", "Timid", "Weak"] },
  { "id": "13", "question": "What is the antonym of 'happy'?", "options": ["Joyful", "Sad", "Excited", "Glad"] },
  { "id": "14", "question": "Which sentence is grammatically correct?", "options": ["They is playing.", "They are playing.", "They playing.", "They be playing."] },
  { "id": "15", "question": "What does the word 'sincere' mean?", "options": ["Honest", "Deceitful", "Fake", "Dishonest"] },
  { "id": "16", "question": "What is the synonym of 'quick'?", "options": ["Fast", "Slow", "Steady", "Sluggish"] },
  { "id": "17", "question": "Choose the correct spelling.", "options": ["Definately", "Definitely", "Definitly", "Definately"] },
  { "id": "18", "question": "What is the antonym of 'rich'?", "options": ["Wealthy", "Poor", "Affluent", "Comfortable"] },
  { "id": "19", "question": "What is the meaning of 'arduous'?", "options": ["Easy", "Hard", "Simple", "Light"] },
  { "id": "20", "question": "Which of the following is a synonym for 'diligent'?", "options": ["Lazy", "Hardworking", "Careless", "Negligent"] },
  { "id": "21", "question": "What is the synonym of 'beautiful'?", "options": ["Ugly", "Pretty", "Unpleasant", "Horrible"] },
  { "id": "22", "question": "Choose the correctly spelled word.", "options": ["Occasion", "Ocassion", "Occassion", "Occasions"] },
  { "id": "23", "question": "What is the antonym of 'optimistic'?", "options": ["Pessimistic", "Hopeful", "Positive", "Cheerful"] },
  { "id": "24", "question": "Choose the correct form of the verb: 'He ____ to the party last night.'", "options": ["go", "went", "gone", "going"] },
  { "id": "25", "question": "What is the meaning of 'audacious'?", "options": ["Timid", "Fearless", "Cowardly", "Hesitant"] },
  { "id": "26", "question": "Which of the following sentences is correct?", "options": ["She don't like ice cream.", "She doesn't likes ice cream.", "She doesn't like ice cream.", "She not like ice cream."] },
  { "id": "27", "question": "What does the word 'fortuitous' mean?", "options": ["Unfortunate", "Accidental", "Planned", "Deliberate"] },
  { "id": "28", "question": "What is the synonym of 'angry'?", "options": ["Furious", "Happy", "Joyful", "Calm"] },
  { "id": "29", "question": "Which word is opposite to 'early'?", "options": ["Late", "Prompt", "Timely", "On-time"] },
  { "id": "30", "question": "What is the meaning of 'tranquil'?", "options": ["Noisy", "Calm", "Busy", "Chaotic"] },
  { "id": "31", "question": "Choose the correct form of the verb: 'They ____ to the market every Saturday.'", "options": ["go", "goes", "gone", "going"] },
  { "id": "32", "question": "What is the synonym of 'famous'?", "options": ["Unknown", "Renowned", "Obscure", "Common"] },
  { "id": "33", "question": "What is the antonym of 'tall'?", "options": ["Short", "High", "Big", "Large"] },
  { "id": "34", "question": "Which sentence is grammatically correct?", "options": ["He have a car.", "He has a car.", "He haves a car.", "He is have a car."] },
  { "id": "35", "question": "What does the word 'gregarious' mean?", "options": ["Shy", "Sociable", "Reserved", "Lonely"] },
  { "id": "36", "question": "What is the synonym of 'cautious'?", "options": ["Careless", "Prudent", "Reckless", "Impulsive"] },
  { "id": "37", "question": "Choose the correct spelling.", "options": ["Acquaintance", "Acquaintence", "Aqaintance", "Aqaintence"] },
  { "id": "38", "question": "What is the antonym of 'hard'?", "options": ["Soft", "Difficult", "Tough", "Firm"] },
  { "id": "39", "question": "What is the meaning of 'meticulous'?", "options": ["Careless", "Detailed", "Simple", "Quick"] },
  { "id": "40", "question": "Which of the following is a synonym for 'serene'?", "options": ["Calm", "Anxious", "Disturbed", "Agitated"] },
  { "id": "41", "question": "What is the synonym of 'happy'?", "options": ["Sad", "Joyful", "Angry", "Tired"] },
  { "id": "42", "question": "What is the antonym of 'difficult'?", "options": ["Hard", "Easy", "Challenging", "Tough"] },
  { "id": "43", "question": "Choose the correct sentence.", "options": ["She go to the store.", "She goes to the store.", "She going to the store.", "She gone to the store."] },
  { "id": "44", "question": "Which word is spelled correctly?", "options": ["Accommodate", "Acommodate", "Accomodate", "Acommodate"] },
  { "id": "45", "question": "What is the past tense of 'run'?", "options": ["Ran", "Runned", "Running", "Rans"] },
  { "id": "46", "question": "What is the opposite of 'light'?", "options": ["Heavy", "Bright", "Dark", "Dim"] },
  { "id": "47", "question": "Choose the correct plural form of 'child'.", "options": ["Childs", "Childes", "Children", "Childrens"] },
  { "id": "48", "question": "What is the main idea of a text?", "options": ["A summary", "A conclusion", "The primary point", "A detail"] },
  { "id": "49", "question": "What does 'benevolent' mean?", "options": ["Kind", "Cruel", "Selfish", "Generous"] },
  { "id": "50", "question": "Which sentence is a question?", "options": ["She is going to the park.", "Is she going to the park?", "She went to the park.", "She goes to the park."] },
  { "id": "51", "question": "What is a synonym for 'quick'?", "options": ["Slow", "Fast", "Steady", "Lazy"] },
  { "id": "52", "question": "Choose the correct form of 'to be'.", "options": ["He are happy.", "He is happy.", "He am happy.", "He be happy."] },
  { "id": "53", "question": "What is the meaning of 'to comprehend'?", "options": ["To ignore", "To understand", "To forget", "To remember"] },
  { "id": "54", "question": "Which of the following is a compound sentence?", "options": ["I like apples.", "I like apples, and I like oranges.", "I like apples and.", "I like apples, but."] },
  { "id": "55", "question": "What is the antonym of 'noisy'?", "options": ["Silent", "Loud", "Quiet", "Blaring"] },
  { "id": "56", "question": "What is the main purpose of a conclusion?", "options": ["To summarize", "To introduce", "To explain", "To argue"] },
  { "id": "57", "question": "What is the plural of 'mouse'?", "options": ["Mouses", "Mice", "Mices", "Mouse"] },
  { "id": "58", "question": "Which of the following is a synonym for 'difficult'?", "options": ["Simple", "Challenging", "Easy", "Straightforward"] },
  { "id": "59", "question": "Choose the correctly punctuated sentence.", "options": ["Lets eat Grandma.", "Let's eat, Grandma.", "Lets eat, Grandma.", "Let’s eat Grandma."] },
  { "id": "60", "question": "What does 'meticulous' mean?", "options": ["Careless", "Careful", "Lazy", "Rushed"] },
  { "id": "61", "question": "What is a synonym for 'happy'?", "options": ["Sad", "Joyful", "Angry", "Tired"] },
  { "id": "62", "question": "What does 'diligent' mean?", "options": ["Lazy", "Hardworking", "Quick", "Rude"] },
  { "id": "63", "question": "Choose the correct sentence.", "options": ["He don't like ice cream.", "He doesn't like ice cream.", "He doesn't likes ice cream.", "He not like ice cream."] },
  { "id": "64", "question": "Which word is spelled correctly?", "options": ["Occasion", "Occassion", "Occassion", "Occasionn"] },
  { "id": "65", "question": "What is the past tense of 'eat'?", "options": ["Eated", "Ate", "Eating", "Eats"] },
  { "id": "66", "question": "What is the opposite of 'bright'?", "options": ["Dim", "Light", "Shiny", "Dark"] },
  { "id": "67", "question": "Choose the correct plural form of 'tooth'.", "options": ["Tooths", "Teeth", "Toothes", "Teeths"] },
  { "id": "68", "question": "What is the main idea of a text?", "options": ["The conclusion", "The primary point", "A detail", "A summary"] },
  { "id": "69", "question": "What does 'meticulous' mean?", "options": ["Careless", "Careful", "Lazy", "Rushed"] },
  { "id": "70", "question": "Which sentence is a question?", "options": ["She is happy.", "Is she happy?", "She happy?", "She is going."] },
  { "id": "71", "question": "What is a synonym for 'fast'?", "options": ["Slow", "Quick", "Steady", "Lazy"] },
  { "id": "72", "question": "Choose the correct form of 'to be'.", "options": ["They is friends.", "They are friends.", "They am friends.", "They be friends."] },
  { "id": "73", "question": "What does 'contemplate' mean?", "options": ["To ignore", "To think about", "To forget", "To remember"] },
  { "id": "74", "question": "Which of the following is a compound sentence?", "options": ["I like tea.", "I like tea, and I like coffee.", "I like tea and.", "I like tea, but."] },
  { "id": "75", "question": "What is the antonym of 'clean'?", "options": ["Dirty", "Clear", "Pure", "Fresh"] },
  { "id": "76", "question": "What is the main purpose of a thesis statement?", "options": ["To summarize", "To introduce the topic", "To explain", "To argue"] },
  { "id": "77", "question": "What is the plural of 'goose'?", "options": ["Gooses", "Geese", "Geeses", "Goosen"] },
  { "id": "78", "question": "Which of the following is a synonym for 'difficult'?", "options": ["Easy", "Simple", "Challenging", "Clear"] },
  { "id": "79", "question": "Choose the correctly punctuated sentence.", "options": ["Lets go home.", "Let's go home.", "Lets go, home.", "Let’s go, home."] },
  { "id": "80", "question": "What is the meaning of 'ambiguous'?", "options": ["Clear", "Uncertain", "Certain", "Straightforward"] },
  { "id": "81", "question": "What is a synonym for 'begin'?", "options": ["Start", "End", "Continue", "Pause"] },
  { "id": "82", "question": "Choose the correct sentence.", "options": ["They goes to school.", "They go to school.", "They going to school.", "They gone to school."] },
  { "id": "83", "question": "What is an antonym for 'difficult'?", "options": ["Easy", "Hard", "Complicated", "Challenging"] },
  { "id": "84", "question": "What does 'benevolent' mean?", "options": ["Mean", "Kind", "Selfish", "Rude"] },
  { "id": "85", "question": "Choose the correct past tense form of 'see'.", "options": ["Seed", "Saw", "Seen", "Seeing"] },
  { "id": "86", "question": "What is the meaning of 'rejuvenate'?", "options": ["To make young again", "To grow old", "To tire", "To sleep"] },
  { "id": "87", "question": "What is a synonym for 'beautiful'?", "options": ["Pretty", "Ugly", "Plain", "Normal"] },
  { "id": "88", "question": "What is the main idea of a paragraph?", "options": ["A minor detail", "The primary focus", "A conclusion", "An opinion"] },
  { "id": "89", "question": "Choose the correctly punctuated sentence.", "options": ["Its a nice day.", "It's a nice day.", "Its' a nice day.", "It a nice day."] },
  { "id": "90", "question": "What is the plural of 'child'?", "options": ["Childs", "Children", "Childrens", "Childes"] },
  { "id": "91", "question": "What does 'transient' mean?", "options": ["Permanent", "Temporary", "Long-lasting", "Stable"] },
  { "id": "92", "question": "Which word is spelled incorrectly?", "options": ["Accommodate", "Definite", "Occasion", "Acomodate"] },
  { "id": "93", "question": "What is the antonym of 'expand'?", "options": ["Shrink", "Grow", "Increase", "Enlarge"] },
  { "id": "94", "question": "Choose the correct form of 'to have'.", "options": ["They has a car.", "They have a car.", "They having a car.", "They have car."] },
  { "id": "95", "question": "What does 'impeccable' mean?", "options": ["Flawed", "Perfect", "Bad", "Faulty"] },
  { "id": "96", "question": "What is a synonym for 'brave'?", "options": ["Cowardly", "Fearful", "Courageous", "Weak"] },
  { "id": "97", "question": "What is the past tense of 'go'?", "options": ["Went", "Gone", "Goes", "Going"] },
  { "id": "98", "question": "Which sentence is a command?", "options": ["Please sit down.", "She is sitting down.", "He sits down.", "They are sitting."] },
  { "id": "99", "question": "What does 'conundrum' mean?", "options": ["Puzzle", "Solution", "Answer", "Question"] },
  { "id": "100", "question": "What is a synonym for 'happy'?", "options": ["Sad", "Joyful", "Angry", "Upset"] },


]
;

var gk=[
  { "id": "1", "question": "Who is the current President of the United States?", "options": ["Joe Biden", "Donald Trump", "Barack Obama", "George Bush"] },
  { "id": "2", "question": "What is the capital city of Japan?", "options": ["Tokyo", "Beijing", "Seoul", "Bangkok"] },
  { "id": "3", "question": "In which year did World War II end?", "options": ["1945", "1944", "1946", "1947"] },
  { "id": "4", "question": "Who wrote the national anthem of India?", "options": ["Rabindranath Tagore", "Bankim Chandra Chatterjee", "Sarojini Naidu", "Mahatma Gandhi"] },
  { "id": "5", "question": "Which is the largest continent in the world?", "options": ["Asia", "Africa", "North America", "Europe"] },
  { "id": "6", "question": "What is the currency of the United Kingdom?", "options": ["Pound", "Dollar", "Euro", "Yen"] },
  { "id": "7", "question": "Who was the first man to step on the Moon?", "options": ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"] },
  { "id": "8", "question": "Which is the largest ocean on Earth?", "options": ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"] },
  { "id": "9", "question": "Who is known as the Father of the Nation in India?", "options": ["Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "Bhagat Singh"] },
  { "id": "10", "question": "Which year did India gain independence?", "options": ["1947", "1945", "1950", "1948"] },
  { "id": "11", "question": "What is the national flower of India?", "options": ["Lotus", "Rose", "Sunflower", "Lily"] },
  { "id": "12", "question": "Which planet is known as the Red Planet?", "options": ["Mars", "Jupiter", "Saturn", "Venus"] },
  { "id": "13", "question": "Who invented the light bulb?", "options": ["Thomas Edison", "Albert Einstein", "Nikola Tesla", "Alexander Bell"] },
  { "id": "14", "question": "Which is the longest river in the world?", "options": ["Nile", "Amazon", "Yangtze", "Mississippi"] },
  { "id": "15", "question": "In which year did the Titanic sink?", "options": ["1912", "1910", "1914", "1916"] },
  { "id": "16", "question": "Who discovered penicillin?", "options": ["Alexander Fleming", "Marie Curie", "Isaac Newton", "Albert Einstein"] },
  { "id": "17", "question": "Which country is known as the Land of the Rising Sun?", "options": ["Japan", "China", "Thailand", "India"] },
  { "id": "18", "question": "What is the smallest country in the world?", "options": ["Vatican City", "Monaco", "Malta", "San Marino"] },
  { "id": "19", "question": "Who painted the Mona Lisa?", "options": ["Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso", "Michelangelo"] },
  { "id": "20", "question": "Which is the largest planet in our solar system?", "options": ["Jupiter", "Saturn", "Mars", "Neptune"] },
  { "id": "21", "question": "Which animal is known as the Ship of the Desert?", "options": ["Camel", "Horse", "Elephant", "Lion"] },
  { "id": "22", "question": "Who was the first female Prime Minister of India?", "options": ["Indira Gandhi", "Sonia Gandhi", "Pratibha Patil", "Sarojini Naidu"] },
  { "id": "23", "question": "What is the chemical symbol for water?", "options": ["H2O", "O2", "CO2", "NaCl"] },
  { "id": "24", "question": "Which planet is closest to the Sun?", "options": ["Mercury", "Venus", "Mars", "Earth"] },
  { "id": "25", "question": "Who invented the telephone?", "options": ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "James Watt"] },
  { "id": "26", "question": "Which is the largest mammal on Earth?", "options": ["Blue Whale", "Elephant", "Giraffe", "Hippopotamus"] },
  { "id": "27", "question": "What is the largest desert in the world?", "options": ["Sahara", "Gobi", "Arabian", "Kalahari"] },
  { "id": "28", "question": "In which city is the Eiffel Tower located?", "options": ["Paris", "London", "Rome", "Berlin"] },
  { "id": "29", "question": "What is the national bird of India?", "options": ["Peacock", "Sparrow", "Eagle", "Crow"] },
  { "id": "30", "question": "What is the capital of Australia?", "options": ["Canberra", "Sydney", "Melbourne", "Brisbane"] },
  { "id": "31", "question": "What is the national sport of Canada?", "options": ["Ice Hockey", "Basketball", "Baseball", "Soccer"] },
  { "id": "32", "question": "Which gas is most abundant in the Earth's atmosphere?", "options": ["Nitrogen", "Oxygen", "Carbon Dioxide", "Helium"] },
  { "id": "33", "question": "Who is known as the Father of Geometry?", "options": ["Euclid", "Aristotle", "Pythagoras", "Archimedes"] },
  { "id": "34", "question": "Which planet is known as the Evening Star?", "options": ["Venus", "Mars", "Jupiter", "Saturn"] },
  { "id": "35", "question": "Which country is famous for the Great Wall?", "options": ["China", "Japan", "India", "Vietnam"] },
  { "id": "36", "question": "What is the capital of Canada?", "options": ["Ottawa", "Toronto", "Vancouver", "Montreal"] },
  { "id": "37", "question": "Which element has the chemical symbol O?", "options": ["Oxygen", "Gold", "Osmium", "Oganesson"] },
  { "id": "38", "question": "Which instrument measures atmospheric pressure?", "options": ["Barometer", "Thermometer", "Anemometer", "Hygrometer"] },
  { "id": "39", "question": "Who discovered gravity?", "options": ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"] },
  { "id": "40", "question": "What is the smallest bone in the human body?", "options": ["Stapes", "Femur", "Tibia", "Fibula"] },
  { "id": "41", "question": "Who is known as the Iron Man of India?", "options": ["Sardar Patel", "Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose"] },
  { "id": "42", "question": "What is the hardest natural substance on Earth?", "options": ["Diamond", "Gold", "Iron", "Graphite"] },
  { "id": "43", "question": "Which planet is known as the Blue Planet?", "options": ["Earth", "Uranus", "Neptune", "Mars"] },
  { "id": "44", "question": "In which country is Mount Everest located?", "options": ["Nepal", "China", "India", "Bhutan"] },
  { "id": "45", "question": "What is the national fruit of India?", "options": ["Mango", "Apple", "Banana", "Orange"] },
  { "id": "46", "question": "Who is known as the Nightingale of India?", "options": ["Sarojini Naidu", "Indira Gandhi", "Lata Mangeshkar", "Kalpana Chawla"] },
  { "id": "47", "question": "Which is the largest freshwater lake in the world?", "options": ["Lake Superior", "Lake Victoria", "Lake Baikal", "Caspian Sea"] },
  { "id": "48", "question": "Which is the longest bone in the human body?", "options": ["Femur", "Tibia", "Humerus", "Fibula"] },
  { "id": "49", "question": "Who was the first President of the United States?", "options": ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"] },
  { "id": "50", "question": "What is the largest island in the world?", "options": ["Greenland", "New Guinea", "Borneo", "Madagascar"] },
  { "id": "51", "question": "Which country is known as the Land of White Elephants?", "options": ["Thailand", "India", "Sri Lanka", "Myanmar"] },
  { "id": "52", "question": "What is the longest river in Asia?", "options": ["Yangtze", "Ganges", "Mekong", "Indus"] },
  { "id": "53", "question": "Who developed the theory of relativity?", "options": ["Albert Einstein", "Isaac Newton", "Nikola Tesla", "Galileo Galilei"] },
  { "id": "54", "question": "Which is the largest internal organ in the human body?", "options": ["Liver", "Heart", "Kidney", "Lungs"] },
  { "id": "55", "question": "What is the capital of Russia?", "options": ["Moscow", "Saint Petersburg", "Kiev", "Sochi"] },
  { "id": "56", "question": "Which planet is known as the Morning Star?", "options": ["Venus", "Mars", "Jupiter", "Saturn"] },
  { "id": "57", "question": "What is the smallest planet in our solar system?", "options": ["Mercury", "Mars", "Venus", "Pluto"] },
  { "id": "58", "question": "What is the hardest part of the human body?", "options": ["Tooth Enamel", "Skull", "Femur", "Nails"] },
  { "id": "59", "question": "Which country gifted the Statue of Liberty to the United States?", "options": ["France", "Germany", "Italy", "Spain"] },
  { "id": "60", "question": "What is the main gas found in the air we breathe?", "options": ["Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen"] },
  { "id": "61", "question": "What is the national flower of Japan?", "options": ["Cherry Blossom", "Rose", "Sunflower", "Lily"] },
  { "id": "62", "question": "Who is known as the 'Light of Asia'?", "options": ["Gautama Buddha", "Confucius", "Mahatma Gandhi", "Laozi"] },
  { "id": "63", "question": "Which country has the longest coastline in the world?", "options": ["Canada", "Australia", "Russia", "USA"] },
  { "id": "64", "question": "What is the boiling point of water at sea level?", "options": ["100°C", "90°C", "80°C", "70°C"] },
  { "id": "65", "question": "Which planet is known as the Red Planet?", "options": ["Mars", "Jupiter", "Saturn", "Venus"] },
  { "id": "66", "question": "Who was the first woman to go to space?", "options": ["Valentina Tereshkova", "Sally Ride", "Kalpana Chawla", "Mae Jemison"] },
  { "id": "67", "question": "What is the most spoken language in the world?", "options": ["English", "Mandarin Chinese", "Hindi", "Spanish"] },
  { "id": "68", "question": "What is the largest continent by land area?", "options": ["Asia", "Africa", "North America", "Europe"] },
  { "id": "69", "question": "Which is the national game of Japan?", "options": ["Sumo Wrestling", "Baseball", "Soccer", "Rugby"] },
  { "id": "70", "question": "Who painted the Sistine Chapel ceiling?", "options": ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"] },
  { "id": "71", "question": "Which is the largest ocean on Earth?", "options": ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"] },
  { "id": "72", "question": "Who wrote 'To Kill a Mockingbird'?", "options": ["Harper Lee", "Mark Twain", "Ernest Hemingway", "F. Scott Fitzgerald"] },
  { "id": "73", "question": "What is the capital city of Australia?", "options": ["Canberra", "Sydney", "Melbourne", "Brisbane"] },
  { "id": "74", "question": "Which country is known for the pyramids?", "options": ["Egypt", "Mexico", "China", "India"] },
  { "id": "75", "question": "What is the longest river in the world?", "options": ["Nile", "Amazon", "Yangtze", "Mississippi"] },
  { "id": "76", "question": "What is the smallest country in the world?", "options": ["Vatican City", "Monaco", "Malta", "San Marino"] },
  { "id": "77", "question": "Which gas is most abundant in the Earth's atmosphere?", "options": ["Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen"] },
  { "id": "78", "question": "Who was the first woman to win a Nobel Prize?", "options": ["Marie Curie", "Jane Addams", "Rosalind Franklin", "Malala Yousafzai"] },
  { "id": "79", "question": "Which continent is known as the Dark Continent?", "options": ["Africa", "Asia", "Australia", "South America"] },
  { "id": "80", "question": "What is the main ingredient in guacamole?", "options": ["Avocado", "Tomato", "Pepper", "Onion"] },
{ "id": "81", "question": "Which gas do plants absorb from the atmosphere?", "options": ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"] },
  { "id": "82", "question": "Which is the largest land animal?", "options": ["Elephant", "Rhino", "Giraffe", "Hippopotamus"] },
  { "id": "83", "question": "What is the capital of Italy?", "options": ["Rome", "Venice", "Florence", "Milan"] },
  { "id": "84", "question": "Who wrote the play 'Romeo and Juliet'?", "options": ["William Shakespeare", "Charles Dickens", "Mark Twain", "George Orwell"] },
  { "id": "85", "question": "What is the largest ocean on Earth?", "options": ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"] },
  { "id": "86", "question": "Who was the first man in space?", "options": ["Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "John Glenn"] },
  { "id": "87", "question": "What is the chemical symbol for gold?", "options": ["Au", "Ag", "Pb", "Fe"] },
  { "id": "88", "question": "Which planet is known for its rings?", "options": ["Saturn", "Jupiter", "Uranus", "Neptune"] },
  { "id": "89", "question": "What is the capital of France?", "options": ["Paris", "Berlin", "Madrid", "Lisbon"] },
  { "id": "90", "question": "Which is the smallest continent?", "options": ["Australia", "Antarctica", "Europe", "South America"] },
  { "id": "91", "question": "What is the currency of Japan?", "options": ["Yen", "Won", "Dollar", "Rupee"] },
  { "id": "92", "question": "Who is known as the 'Father of Computers'?", "options": ["Charles Babbage", "Alan Turing", "Bill Gates", "Steve Jobs"] },
  { "id": "93", "question": "Which country is known as the Land of the Rising Sun?", "options": ["Japan", "China", "India", "Thailand"] },
  { "id": "94", "question": "Who painted the ceiling of the Sistine Chapel?", "options": ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"] },
  { "id": "95", "question": "What is the largest mammal in the world?", "options": ["Blue Whale", "Elephant", "Giraffe", "Great White Shark"] },
  { "id": "96", "question": "Which is the fastest land animal?", "options": ["Cheetah", "Lion", "Tiger", "Gazelle"] },
  { "id": "97", "question": "What is the most widely spoken language in the world?", "options": ["Mandarin Chinese", "Spanish", "English", "Hindi"] },
  { "id": "98", "question": "Which country is famous for kangaroos?", "options": ["Australia", "New Zealand", "Canada", "India"] },
  { "id": "99", "question": "What is the main ingredient in guacamole?", "options": ["Avocado", "Tomato", "Onion", "Pepper"] },
  { "id": "100", "question": "What is the smallest country in the world?", "options": ["Vatican City", "Monaco", "Malta", "San Marino"] },




]
;

var maths=[
  { "id": "1", "question": "What is the area of a circle with a radius of 7 cm?", "options": ["154 sq cm", "150 sq cm", "140 sq cm", "160 sq cm"] },
  { "id": "2", "question": "If 5x - 3 = 2x + 12, what is the value of x?", "options": ["4", "5", "6", "7"] },
  { "id": "3", "question": "If the perimeter of a square is 20 cm, what is the length of one side?", "options": ["4 cm", "5 cm", "6 cm", "7 cm"] },
  { "id": "4", "question": "If a car travels at 60 km/h for 2 hours, how far does it travel?", "options": ["120 km", "110 km", "130 km", "140 km"] },
  { "id": "5", "question": "What is the value of 3^2 + 4^2?", "options": ["25", "24", "26", "27"] },
  { "id": "6", "question": "If a rectangle has a length of 10 cm and a width of 5 cm, what is its area?", "options": ["50 sq cm", "45 sq cm", "60 sq cm", "55 sq cm"] },
  { "id": "7", "question": "What is the value of the square root of 144?", "options": ["12", "11", "13", "14"] },
  { "id": "8", "question": "If an item costs $50 and there is a 10% discount, what is the discount amount?", "options": ["$5", "$10", "$15", "$20"] },
  { "id": "9", "question": "What is the area of a triangle with base 10 cm and height 5 cm?", "options": ["25 sq cm", "30 sq cm", "35 sq cm", "40 sq cm"] },
  { "id": "10", "question": "What is the perimeter of a square with side 6 cm?", "options": ["24 cm", "26 cm", "28 cm", "30 cm"] },
{ "id": "11", "question": "What is the cube root of 27?", "options": ["3", "9", "6", "4"] },
  { "id": "12", "question": "If a book costs $45 and there is a 15% discount, what is the discount amount?", "options": ["$6.75", "$7.00", "$6.00", "$7.50"] },
  { "id": "13", "question": "What is the area of a rectangle with a length of 15 cm and width of 4 cm?", "options": ["60 sq cm", "45 sq cm", "75 sq cm", "70 sq cm"] },
  { "id": "14", "question": "If a car travels 80 km/h for 1.5 hours, how far does it travel?", "options": ["120 km", "115 km", "110 km", "125 km"] },
  { "id": "15", "question": "What is the value of 7^2 - 3^2?", "options": ["40", "45", "44", "46"] },
  { "id": "16", "question": "What is the area of a square with side 9 cm?", "options": ["81 sq cm", "90 sq cm", "85 sq cm", "75 sq cm"] },
  { "id": "17", "question": "If 15% of a number is 45, what is the number?", "options": ["300", "250", "270", "280"] },
  { "id": "18", "question": "What is the value of 6 x 7 + 5?", "options": ["47", "51", "50", "49"] },
  { "id": "19", "question": "If a train travels 150 km in 2.5 hours, what is its speed?", "options": ["60 km/h", "70 km/h", "55 km/h", "65 km/h"] },
  { "id": "20", "question": "What is the value of (12 - 5) x 4?", "options": ["28", "32", "24", "30"] },
{ "id": "21", "question": "What is the sum of angles in a triangle?", "options": ["180°", "360°", "90°", "270°"] },
  { "id": "22", "question": "If a car travels 240 km in 3 hours, what is its speed?", "options": ["80 km/h", "90 km/h", "70 km/h", "60 km/h"] },
  { "id": "23", "question": "What is the square of 15?", "options": ["225", "230", "215", "200"] },
  { "id": "24", "question": "If a product costs $80 after a 20% discount, what was the original price?", "options": ["$100", "$90", "$120", "$110"] },
  { "id": "25", "question": "What is the value of 9 x 9 - 7?", "options": ["74", "81", "75", "72"] },
  { "id": "26", "question": "If a circle has a diameter of 14 cm, what is its radius?", "options": ["7 cm", "6 cm", "8 cm", "9 cm"] },
  { "id": "27", "question": "What is the area of a square with side length 8 cm?", "options": ["64 sq cm", "72 sq cm", "80 sq cm", "56 sq cm"] },
  { "id": "28", "question": "What is the value of (25 - 10) ÷ 5?", "options": ["3", "2", "4", "5"] },
  { "id": "29", "question": "If 3 pencils cost $1.50, what is the cost of one pencil?", "options": ["$0.50", "$0.75", "$1.00", "$1.25"] },
  { "id": "30", "question": "What is the square root of 225?", "options": ["15", "14", "13", "16"] },

  { "id": "31", "question": "What is the value of 8^3?", "options": ["512", "256", "128", "64"] },
  { "id": "32", "question": "If a person buys a shirt for $120 and sells it for $150, what is his profit?", "options": ["$30", "$20", "$40", "$50"] },
  { "id": "33", "question": "What is the circumference of a circle with a radius of 7 cm? (π = 22/7)", "options": ["44 cm", "42 cm", "40 cm", "38 cm"] },
  { "id": "34", "question": "If x = 2 and y = 3, what is the value of x^2 + y^2?", "options": ["13", "12", "14", "15"] },
  { "id": "35", "question": "What is the area of a rectangle with length 12 cm and width 8 cm?", "options": ["96 sq cm", "98 sq cm", "100 sq cm", "92 sq cm"] },
  { "id": "36", "question": "If a train travels 300 km in 4 hours, what is its speed?", "options": ["75 km/h", "80 km/h", "70 km/h", "85 km/h"] },
  { "id": "37", "question": "What is the value of 15% of 200?", "options": ["30", "25", "35", "40"] },
  { "id": "38", "question": "If the perimeter of a square is 36 cm, what is the length of one side?", "options": ["9 cm", "8 cm", "7 cm", "6 cm"] },
  { "id": "39", "question": "What is the square root of 196?", "options": ["14", "15", "16", "13"] },
  { "id": "40", "question": "If a rectangle has an area of 72 sq cm and a length of 12 cm, what is its width?", "options": ["6 cm", "5 cm", "8 cm", "7 cm"] },
  { "id": "41", "question": "What is the volume of a cube with side length 5 cm?", "options": ["125 cubic cm", "150 cubic cm", "100 cubic cm", "175 cubic cm"] },
  { "id": "42", "question": "If a train travels 540 km in 6 hours, what is its speed?", "options": ["90 km/h", "85 km/h", "95 km/h", "100 km/h"] },
  { "id": "43", "question": "What is the value of (5 + 3) x 2?", "options": ["16", "14", "12", "10"] },
  { "id": "44", "question": "What is the area of a triangle with a base of 12 cm and a height of 6 cm?", "options": ["36 sq cm", "40 sq cm", "32 sq cm", "42 sq cm"] },
  { "id": "45", "question": "If a product costs $200 after a 20% discount, what was the original price?", "options": ["$250", "$240", "$230", "$220"] },
  { "id": "46", "question": "What is the square root of 256?", "options": ["16", "18", "14", "20"] },
  { "id": "47", "question": "If x = 5, what is the value of x^2 + 2x?", "options": ["35", "30", "28", "32"] },
  { "id": "48", "question": "What is the circumference of a circle with a diameter of 10 cm? (π = 3.14)", "options": ["31.4 cm", "32 cm", "28 cm", "33 cm"] },
  { "id": "49", "question": "What is the value of 3^3?", "options": ["27", "21", "18", "24"] },
  { "id": "50", "question": "If the perimeter of a rectangle is 50 cm and its length is 15 cm, what is its width?", "options": ["10 cm", "7.5 cm", "12 cm", "8.5 cm"] },

  { "id": "51", "question": "What is the perimeter of an equilateral triangle with a side length of 10 cm?", "options": ["30 cm", "25 cm", "20 cm", "15 cm"] },
  { "id": "52", "question": "If a train travels 720 km in 9 hours, what is its speed?", "options": ["80 km/h", "90 km/h", "70 km/h", "60 km/h"] },
  { "id": "53", "question": "What is the value of (7 + 3) x (5 - 2)?", "options": ["30", "25", "28", "32"] },
  { "id": "54", "question": "If the radius of a circle is 14 cm, what is its area? (π = 22/7)", "options": ["616 sq cm", "600 sq cm", "580 sq cm", "630 sq cm"] },
  { "id": "55", "question": "What is the value of 5^3?", "options": ["125", "150", "100", "75"] },
  { "id": "56", "question": "What is the volume of a sphere with a radius of 3 cm? (π = 3.14)", "options": ["113.04 cubic cm", "108 cubic cm", "110.4 cubic cm", "105 cubic cm"] },
  { "id": "57", "question": "If a product costs $240 after a 25% discount, what was the original price?", "options": ["$320", "$300", "$340", "$350"] },
  { "id": "58", "question": "What is the value of 12 x 12?", "options": ["144", "132", "150", "140"] },
  { "id": "59", "question": "What is the perimeter of a rectangle with length 20 cm and width 10 cm?", "options": ["60 cm", "55 cm", "50 cm", "45 cm"] },
  { "id": "60", "question": "If x = 4 and y = 5, what is the value of x^2 + y^2?", "options": ["41", "45", "49", "53"] },
  { "id": "61", "question": "If a person buys a laptop for $900 and sells it for $1200, what is his profit?", "options": ["$300", "$200", "$400", "$250"] },
  { "id": "62", "question": "What is the square root of 121?", "options": ["11", "10", "12", "13"] },
  { "id": "63", "question": "What is the value of 9^2?", "options": ["81", "72", "64", "90"] },
  { "id": "64", "question": "If a triangle has two sides of 3 cm and 4 cm, what is the hypotenuse?", "options": ["5 cm", "6 cm", "7 cm", "8 cm"] },
  { "id": "65", "question": "What is the value of (20 ÷ 4) + (5 x 3)?", "options": ["19", "20", "18", "17"] },
  { "id": "66", "question": "What is the circumference of a circle with a radius of 6 cm? (π = 3.14)", "options": ["37.68 cm", "36 cm", "38 cm", "35 cm"] },
  { "id": "67", "question": "What is the area of a square with side length 12 cm?", "options": ["144 sq cm", "150 sq cm", "130 sq cm", "140 sq cm"] },
  { "id": "68", "question": "If the volume of a cube is 64 cubic cm, what is the side length?", "options": ["4 cm", "5 cm", "6 cm", "3 cm"] },
  { "id": "69", "question": "What is the value of 25% of 200?", "options": ["50", "40", "45", "55"] },
  { "id": "70", "question": "What is the value of (7 + 8) x 2?", "options": ["30", "28", "26", "24"] },
  { "id": "71", "question": "What is the value of 1000 - 25% of 1000?", "options": ["750", "800", "700", "900"] },
  { "id": "72", "question": "If a book has 300 pages and you read 50 pages a day, how many days will it take to finish the book?", "options": ["6 days", "5 days", "4 days", "7 days"] },
  { "id": "73", "question": "What is the value of 6 x (3 + 4)?", "options": ["42", "40", "36", "38"] },
  { "id": "74", "question": "If the area of a rectangle is 48 sq cm and the width is 6 cm, what is the length?", "options": ["8 cm", "7 cm", "6 cm", "9 cm"] },
  { "id": "75", "question": "What is 15 x 8?", "options": ["120", "110", "130", "100"] },
  { "id": "76", "question": "What is the value of 12 - 3 x 4?", "options": ["0", "6", "9", "3"] },
  { "id": "77", "question": "If a triangle has sides of lengths 3 cm, 4 cm, and 5 cm, what type of triangle is it?", "options": ["Right-angled", "Isosceles", "Equilateral", "Scalene"] },
  { "id": "78", "question": "What is the value of 40% of 150?", "options": ["60", "70", "80", "50"] },
  { "id": "79", "question": "What is the area of a circle with a radius of 3 cm? (π = 3.14)", "options": ["28.26 sq cm", "27 sq cm", "26 sq cm", "25 sq cm"] },
  { "id": "80", "question": "What is the value of 5! (5 factorial)?", "options": ["120", "100", "125", "150"] },
  { "id": "81", "question": "What is the value of 6 + 6 x 6?", "options": ["42", "36", "48", "60"] },
  { "id": "82", "question": "If a triangle has a base of 10 cm and a height of 5 cm, what is its area?", "options": ["25 sq cm", "30 sq cm", "20 sq cm", "15 sq cm"] },
  { "id": "83", "question": "What is the value of 8^2 + 4^2?", "options": ["80", "64", "48", "80"] },
  { "id": "84", "question": "If a train travels 600 km in 5 hours, what is its speed?", "options": ["120 km/h", "110 km/h", "100 km/h", "90 km/h"] },
  { "id": "85", "question": "What is the area of a trapezoid with bases 10 cm and 20 cm and a height of 5 cm?", "options": ["75 sq cm", "50 sq cm", "70 sq cm", "80 sq cm"] },
  { "id": "86", "question": "If a product costs $500 and there is a 20% discount, what is the sale price?", "options": ["$400", "$350", "$450", "$500"] },
  { "id": "87", "question": "What is the value of 45 ÷ 5 + 6?", "options": ["15", "10", "12", "9"] },
  { "id": "88", "question": "If a person saves $200 per month, how much will he save in 6 months?", "options": ["$1200", "$1000", "$1400", "$1500"] },
  { "id": "89", "question": "What is the value of 2 × (3 + 5)?", "options": ["16", "20", "12", "18"] },
  { "id": "90", "question": "If the side of a cube is 4 cm, what is its volume?", "options": ["64 cubic cm", "60 cubic cm", "50 cubic cm", "70 cubic cm"] },
  { "id": "91", "question": "What is the area of a circle with a radius of 3 cm? (π = 3.14)", "options": ["28.26 sq cm", "28 sq cm", "25 sq cm", "30 sq cm"] },
  { "id": "92", "question": "What is the value of 10 - (6 ÷ 2)?", "options": ["7", "8", "9", "10"] },
  { "id": "93", "question": "What is the sum of the angles in a quadrilateral?", "options": ["360°", "270°", "180°", "90°"] },
  { "id": "94", "question": "If the cost of 5 apples is $3, how much do 20 apples cost?", "options": ["$12", "$15", "$10", "$20"] },
  { "id": "95", "question": "What is the difference between 50 and 17?", "options": ["33", "32", "31", "30"] },
  { "id": "96", "question": "What is the area of a rectangle with length 5 cm and width 3 cm?", "options": ["15 sq cm", "18 sq cm", "20 sq cm", "12 sq cm"] },
  { "id": "97", "question": "What is the value of 11 x 12?", "options": ["132", "120", "140", "150"] },
  { "id": "98", "question": "What is the area of a parallelogram with base 10 cm and height 5 cm?", "options": ["50 sq cm", "40 sq cm", "60 sq cm", "70 sq cm"] },
  { "id": "99", "question": "If 1 kg of flour costs $2, how much does 3 kg cost?", "options": ["$4", "$5", "$6", "$3"] },
  { "id": "100", "question": "What is the value of 2 + 2 x 2?", "options": ["6", "8", "4", "5"] },

  


]
;
  
var science=[
  { "id": "1", "question": "What is the area of a circle with a radius of 7 cm?", "options": ["154 sq cm", "150 sq cm", "140 sq cm", "160 sq cm"] },
  { "id": "2", "question": "If 3x + 5 = 20, what is the value of x?", "options": ["5", "10", "4", "7"] },
  { "id": "3", "question": "A train travels at a speed of 90 km/h. How far will it travel in 2.5 hours?", "options": ["225 km", "240 km", "200 km", "180 km"] },
  { "id": "4", "question": "If a box contains 5 red balls and 7 blue balls, what is the probability of picking a blue ball?", "options": ["5/12", "7/12", "1/2", "1/4"] },
  { "id": "5", "question": "What is the next number in the series: 2, 4, 8, 16, ...?", "options": ["32", "24", "30", "28"] },
  { "id": "6", "question": "If the perimeter of a rectangle is 40 cm and the length is 12 cm, what is the width?", "options": ["8 cm", "10 cm", "12 cm", "6 cm"] },
  { "id": "7", "question": "In a group of 40 people, 15 like tea, 10 like coffee, and 15 like both. How many people like neither?", "options": ["5", "10", "15", "20"] },
  { "id": "8", "question": "What is 15% of 200?", "options": ["30", "25", "35", "20"] },
  { "id": "9", "question": "If a clock shows 3:15, what is the angle between the hour and minute hands?", "options": ["52.5°", "90°", "75°", "60°"] },
  { "id": "10", "question": "How many sides does a dodecagon have?", "options": ["12", "10", "8", "14"] },
  { "id": "11", "question": "If 5 workers can complete a task in 20 days, how many days will it take 10 workers to complete the same task?", "options": ["10 days", "20 days", "15 days", "25 days"] },
  { "id": "12", "question": "What is the median of the following numbers: 3, 5, 1, 4, 2?", "options": ["3", "2", "4", "5"] },
  { "id": "13", "question": "A car travels 240 km in 3 hours. What is its average speed?", "options": ["80 km/h", "70 km/h", "60 km/h", "90 km/h"] },
  { "id": "14", "question": "Which of the following is a prime number?", "options": ["9", "15", "7", "25"] },
  { "id": "15", "question": "If x + y = 10 and x - y = 2, what is the value of x?", "options": ["6", "4", "8", "2"] },
  { "id": "16", "question": "How many degrees are there in a right angle?", "options": ["90°", "180°", "360°", "270°"] },
  { "id": "17", "question": "If a bag contains 4 green marbles, 3 red marbles, and 2 blue marbles, what is the probability of drawing a green marble?", "options": ["4/9", "1/3", "2/9", "3/9"] },
  { "id": "18", "question": "A person has $100 and spends 20% of it. How much money does he have left?", "options": ["$80", "$70", "$60", "$50"] },
  { "id": "19", "question": "If 2x = 8, what is the value of x?", "options": ["2", "3", "4", "5"] },
  { "id": "20", "question": "What is the value of 25% of 300?", "options": ["75", "80", "70", "90"] },
   { "id": "21", "question": "A bag contains 5 red balls and 7 blue balls. What is the probability of picking a red ball?", "options": ["5/12", "7/12", "1/3", "1/2"] },
  { "id": "22", "question": "What is the area of a triangle with a base of 6 cm and a height of 4 cm?", "options": ["12 sq cm", "24 sq cm", "18 sq cm", "30 sq cm"] },
  { "id": "23", "question": "If a car travels at a speed of 80 km/h, how far will it travel in 3 hours?", "options": ["240 km", "300 km", "180 km", "200 km"] },
  { "id": "24", "question": "The sum of three consecutive integers is 72. What is the smallest integer?", "options": ["23", "24", "22", "25"] },
  { "id": "25", "question": "If a rectangle's length is doubled and its width is halved, what happens to its area?", "options": ["It remains the same", "It doubles", "It halves", "It quadruples"] },
  { "id": "26", "question": "If a product costs $80 after a 20% discount, what was the original price?", "options": ["$100", "$90", "$85", "$95"] },
  { "id": "27", "question": "A store sells a shirt for $25 after a 20% discount. What was the original price?", "options": ["$30", "$28", "$26", "$27"] },
  { "id": "28", "question": "What is the next number in the series: 3, 6, 9, 12, ...?", "options": ["15", "18", "21", "14"] },
  { "id": "29", "question": "If a tank can be filled by a pipe in 10 hours, how long will it take for two pipes to fill it?", "options": ["5 hours", "8 hours", "10 hours", "20 hours"] },
  { "id": "30", "question": "A car travels 300 km in 4 hours. What is its average speed?", "options": ["75 km/h", "80 km/h", "70 km/h", "60 km/h"] },
  { "id": "31", "question": "What is the profit percent if an item is bought for $60 and sold for $75?", "options": ["25%", "30%", "20%", "15%"] },
  { "id": "32", "question": "If a clock shows 3:15, what is the angle between the hour and the minute hand?", "options": ["45°", "90°", "75°", "60°"] },
  { "id": "33", "question": "A train travels at 90 km/h. How far will it travel in 1.5 hours?", "options": ["135 km", "150 km", "120 km", "160 km"] },
  { "id": "34", "question": "What is the sum of the first five prime numbers?", "options": ["28", "30", "24", "26"] },
  { "id": "35", "question": "A product is marked up by 30% and sold for $65. What was the cost price?", "options": ["$50", "$55", "$60", "$62"] },
  { "id": "36", "question": "What is 30% of 150?", "options": ["45", "40", "50", "30"] },
  { "id": "37", "question": "If two angles are complementary and one angle is 30°, what is the other angle?", "options": ["60°", "90°", "45°", "30°"] },
  { "id": "38", "question": "If a number is increased by 20% and then decreased by 20%, what is the net change?", "options": ["4%", "2%", "0%", "6%"] },
  { "id": "39", "question": "If a student scores 75 out of 100, what is his percentage?", "options": ["70%", "75%", "80%", "85%"] },
  { "id": "40", "question": "If it takes 5 men 10 days to complete a task, how many days will it take for 10 men to complete the same task?", "options": ["5 days", "10 days", "15 days", "20 days"] },
  { "id": "41", "question": "If the ratio of boys to girls in a class is 3:2 and there are 30 students, how many girls are there?", "options": ["12", "18", "15", "20"] },
  { "id": "42", "question": "A cyclist covers 90 km in 3 hours. What is his speed?", "options": ["30 km/h", "25 km/h", "40 km/h", "20 km/h"] },
  { "id": "43", "question": "If a car travels 180 km in 2 hours, what is its average speed?", "options": ["60 km/h", "80 km/h", "90 km/h", "100 km/h"] },
  { "id": "44", "question": "If 4 pencils cost $1.20, how much do 10 pencils cost?", "options": ["$3.00", "$2.00", "$2.50", "$2.75"] },
  { "id": "45", "question": "A sum of money doubles itself in 5 years. What is the rate of interest?", "options": ["10%", "15%", "20%", "5%"] },
  { "id": "46", "question": "What is the value of x in the equation 2x - 5 = 9?", "options": ["7", "6", "8", "5"] },
  { "id": "47", "question": "If the cost price of a shirt is $40 and the selling price is $50, what is the profit percentage?", "options": ["25%", "30%", "20%", "15%"] },
  { "id": "48", "question": "A clock gains 10 minutes in an hour. How much time will it gain in a day?", "options": ["8 hours", "12 hours", "24 hours", "20 hours"] },
  { "id": "49", "question": "What is the next number in the series: 5, 10, 20, 40, ...?", "options": ["80", "100", "60", "70"] },
  { "id": "50", "question": "If a train travels at 120 km/h, how far will it travel in 2.5 hours?", "options": ["300 km", "250 km", "400 km", "350 km"] },
  { "id": "51", "question": "A bottle can hold 2 liters of water. How many bottles are needed to hold 12 liters?", "options": ["5", "6", "7", "8"] },
  { "id": "52", "question": "If 3 workers can complete a task in 6 days, how long will it take for 9 workers to complete the same task?", "options": ["2 days", "3 days", "4 days", "6 days"] },
  { "id": "53", "question": "If 1 kg of rice costs $2, how much will 5 kg cost?", "options": ["$8", "$9", "$10", "$7"] },
  { "id": "54", "question": "A man spends 25% of his salary on rent and 10% on groceries. What percentage of his salary does he spend on both?", "options": ["35%", "40%", "30%", "20%"] },
  { "id": "55", "question": "What is the perimeter of a rectangle with length 10 cm and width 5 cm?", "options": ["30 cm", "25 cm", "20 cm", "35 cm"] },
  { "id": "56", "question": "A farmer has 120 apples. If he sells them at $0.50 each, how much will he earn?", "options": ["$50", "$60", "$70", "$80"] },
  { "id": "57", "question": "If a book costs $15 and there is a 10% discount, what is the sale price?", "options": ["$13.50", "$14", "$12", "$15"] },
  { "id": "58", "question": "If a car's value depreciates by 20% each year, what will be its value after one year if it was originally worth $10,000?", "options": ["$8,000", "$7,500", "$9,000", "$9,500"] },
  { "id": "59", "question": "What is the total cost of buying 4 books at $7 each?", "options": ["$28", "$30", "$24", "$32"] },
  { "id": "60", "question": "A bag contains 5 red, 3 blue, and 2 green balls. What is the probability of picking a blue ball?", "options": ["1/10", "3/10", "1/5", "2/5"] },
  { "id": "61", "question": "A man can swim 100 meters in 50 seconds. What is his speed in meters per second?", "options": ["1.5 m/s", "2 m/s", "2.5 m/s", "3 m/s"] },
  { "id": "62", "question": "If a train leaves a station at 3 PM and travels at 60 km/h, what distance will it cover by 5 PM?", "options": ["120 km", "90 km", "150 km", "180 km"] },
  { "id": "63", "question": "A book is on sale for 20% off the original price of $25. What is the sale price?", "options": ["$20", "$18", "$22", "$25"] },
  { "id": "64", "question": "If 6 men can complete a work in 10 days, how many men are needed to complete the same work in 5 days?", "options": ["12", "10", "15", "8"] },
  { "id": "65", "question": "A factory produces 500 toys in 8 hours. How many toys does it produce in 1 hour?", "options": ["70", "80", "60", "90"] },
  { "id": "66", "question": "If a person buys 3 apples for $1.50, how much will 12 apples cost?", "options": ["$6.00", "$5.00", "$4.50", "$7.00"] },
  { "id": "67", "question": "What is the average of the following numbers: 10, 20, 30, 40, 50?", "options": ["30", "40", "35", "25"] },
  { "id": "68", "question": "If the circumference of a circle is 31.4 cm, what is the radius?", "options": ["5 cm", "6 cm", "7 cm", "8 cm"] },
  { "id": "69", "question": "If a car travels 240 km in 3 hours, what is its speed in km/h?", "options": ["80 km/h", "70 km/h", "90 km/h", "60 km/h"] },
  { "id": "70", "question": "A gardener plants 40 trees in 5 days. How many trees does he plant in 1 day?", "options": ["6", "8", "10", "5"] },
  { "id": "71", "question": "What is the value of x in the equation 3x + 2 = 11?", "options": ["2", "3", "4", "5"] },
  { "id": "72", "question": "If a car uses 8 liters of fuel for 100 km, how much fuel will it use for 250 km?", "options": ["20 liters", "25 liters", "15 liters", "30 liters"] },
  { "id": "73", "question": "A recipe requires 2 cups of sugar for 4 servings. How many cups of sugar are needed for 10 servings?", "options": ["4.5", "5", "6", "3"] },
  { "id": "74", "question": "What is the total cost of 5 notebooks if each costs $2.50?", "options": ["$10.00", "$12.50", "$15.00", "$7.50"] },
  { "id": "75", "question": "If a rectangle has a length of 12 cm and a width of 5 cm, what is its area?", "options": ["60 sq cm", "70 sq cm", "80 sq cm", "50 sq cm"] },
  { "id": "76", "question": "What is the probability of rolling a 3 on a fair six-sided die?", "options": ["1/6", "1/3", "1/2", "1/4"] },
  { "id": "77", "question": "A laptop costs $800 after a 20% discount. What was the original price?", "options": ["$1000", "$800", "$900", "$850"] },
  { "id": "78", "question": "If you buy 5 kg of rice for $15, how much will 10 kg cost?", "options": ["$30", "$25", "$20", "$35"] },
  { "id": "79", "question": "If a train is moving at a speed of 120 km/h, how long will it take to cover 240 km?", "options": ["1 hour", "2 hours", "3 hours", "4 hours"] },
  { "id": "80", "question": "How many sides does a hexagon have?", "options": ["5", "6", "7", "8"] },
  { "id": "81", "question": "If the sum of two numbers is 50 and one of them is 30, what is the other number?", "options": ["20", "25", "30", "35"] },
  { "id": "82", "question": "A person can type 40 words in a minute. How many words can he type in 10 minutes?", "options": ["300", "400", "500", "600"] },
  { "id": "83", "question": "If a car travels 150 km in 2 hours, what is its average speed?", "options": ["60 km/h", "70 km/h", "75 km/h", "80 km/h"] },
  { "id": "84", "question": "A recipe calls for 3 cups of flour for 12 cookies. How many cups are needed for 36 cookies?", "options": ["6", "7", "8", "9"] },
  { "id": "85", "question": "If a bicycle travels 20 km in 1 hour, how long will it take to travel 60 km?", "options": ["2 hours", "3 hours", "4 hours", "5 hours"] },
  { "id": "86", "question": "If an item costs $80 after a 20% discount, what was the original price?", "options": ["$100", "$90", "$110", "$120"] },
  { "id": "87", "question": "What is the perimeter of a rectangle with length 10 cm and width 4 cm?", "options": ["28 cm", "24 cm", "30 cm", "20 cm"] },
  { "id": "88", "question": "How many days are in 3 weeks?", "options": ["21", "14", "28", "30"] },
  { "id": "89", "question": "If a train travels 180 km in 3 hours, what is its speed in km/h?", "options": ["50 km/h", "60 km/h", "70 km/h", "80 km/h"] },
  { "id": "90", "question": "If 4 workers can complete a job in 10 days, how long will it take 8 workers to complete the same job?", "options": ["5 days", "10 days", "8 days", "6 days"] },
  { "id": "91", "question": "If a person has 15 apples and gives away 7, how many does he have left?", "options": ["8", "7", "9", "10"] },
  { "id": "92", "question": "What is the area of a triangle with a base of 10 cm and height of 5 cm?", "options": ["25 sq cm", "30 sq cm", "20 sq cm", "15 sq cm"] },
  { "id": "93", "question": "If a car consumes 5 liters of fuel to travel 100 km, how much fuel will it consume to travel 250 km?", "options": ["10 liters", "15 liters", "12 liters", "20 liters"] },
  { "id": "94", "question": "What is the average of the following numbers: 2, 4, 6, 8, 10?", "options": ["5", "6", "7", "8"] },
  { "id": "95", "question": "How many sides does a pentagon have?", "options": ["4", "5", "6", "7"] },
  { "id": "96", "question": "If 10% of a number is 20, what is the number?", "options": ["200", "250", "300", "400"] },
  { "id": "97", "question": "What is the value of 12 squared?", "options": ["144", "124", "156", "132"] },
  { "id": "98", "question": "A box contains 10 red balls and 5 green balls. What is the probability of drawing a red ball?", "options": ["1/2", "2/3", "5/8", "1/3"] },
  { "id": "99", "question": "If a person jogs 3 km every day for 7 days, how many kilometers does he jog in total?", "options": ["18 km", "21 km", "15 km", "24 km"] },
  { "id": "100", "question": "If a book costs $15 and you buy 4 books, how much do you spend?", "options": ["$60", "$55", "$50", "$45"] },





]
;
var ind={};

function generate(sub,key){
    var arr=[];
    var in1=[];
    var c=0;
    while (in1.length < sub.length && c<25)  {
        var rand=Math.floor(Math.random()*sub.length);
        if(in1.includes(rand))
            continue;
        in1.push(rand);
    //    const data= sub.filter(ele=>{ele.id==rand})
       arr.push(sub[rand]);
       c++;
    }
    ind[key]=in1;
    console.log(arr);
    return arr;
}

const SendData=async(req,res)=>{
    const English=generate(english,"english1");
    const Science=generate(science,"science1");
    const Maths=generate(maths,"maths1"); 
    const Gk=generate(gk,"general_awareness1");
    var subjects=[English,Gk,Maths,Science];
    console.log(ind)
    return res.status(200).json(subjects);
}
exports.SendData=SendData;
exports.ind=ind;