export default[
    {
        id: '1',
        post_title: 'SSC CHSL 2024 - Apply Online for 500 Posts',
        post_name: 'SSC CHSL Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '500',
        post_information: 'The Staff Selection Commission (SSC) has announced the recruitment of 500 Lower Division Clerks (LDC) through the CHSL exam. Candidates interested in the vacancy details & fulfilling all eligibility criteria can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 200/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online (including Edit/Modification of Application by candidates & Payment of Application Fees/ Intimation Charges): 30-11-2024',
        post_imp3: 'Candidates are required to register on the SSC portal before applying for the CHSL exam.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 27 Years',
        pdf_filename: 'SSC-CHSL.pdf'
    },
    {
        id: '2',
        post_title: 'SSC CGL 2024 - Combined Graduate Level Examination',
        post_name: 'SSC CGL Online Form 2024',
        post_date: '05-11-2024',
        post_update: '05-11-2024',
        post_vacancy: '8000',
        post_information: 'The Staff Selection Commission (SSC) is conducting the Combined Graduate Level Examination for the recruitment of various posts. Interested candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 05-11-2024',
        post_imp2: 'Last Date for Apply Online: 05-12-2024',
        post_imp3: 'Candidates must have a Bachelor\'s Degree to apply.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 32 Years',
        pdf_filename: 'SSC-CGL.pdf'
    },
    {
        id: '3',
        post_title: 'SSC MTS 2024 - Multi Tasking Staff Recruitment',
        post_name: 'SSC MTS Online Form 2024',
        post_date: '10-11-2024',
        post_update: '10-11-2024',
        post_vacancy: '2000',
        post_information: 'The Staff Selection Commission (SSC) invites applications for the recruitment of Multi Tasking Staff (MTS). Candidates interested in this vacancy can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: No Fee',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 10-11-2024',
        post_imp2: 'Last Date for Apply Online: 15-12-2024',
        post_imp3: 'Candidates must have passed 10th Grade to apply.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 25 Years',
        pdf_filename: 'SSC-MTS.pdf'
    },
    {
        id: '4',
        post_title: 'Bihar SSC - Stenographer Recruitment 2024',
        post_name: 'Bihar SSC Stenographer Online Form 2024',
        post_date: '12-11-2024',
        post_update: '12-11-2024',
        post_vacancy: '300',
        post_information: 'The Bihar Staff Selection Commission (BSSC) has released a notification for the recruitment of Stenographers. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 300/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 150/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 12-11-2024',
        post_imp2: 'Last Date for Apply Online: 10-12-2024',
        post_imp3: 'Candidates should have passed 12th Grade with Steno qualification.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 30 Years',
        pdf_filename: 'Bihar-SSC-Steno.pdf'
    },
    {
        id: '5',
        post_title: 'Uttar Pradesh SSC - Jail Warder Recruitment 2024',
        post_name: 'UP SSC Jail Warder Online Form 2024',
        post_date: '15-11-2024',
        post_update: '15-11-2024',
        post_vacancy: '500',
        post_information: 'Uttar Pradesh Staff Selection Commission (UPSSSC) is recruiting Jail Warders. Interested candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 200/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 15-11-2024',
        post_imp2: 'Last Date for Apply Online: 15-12-2024',
        post_imp3: 'Candidates must have passed 12th Grade to apply.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 25 Years',
        pdf_filename: 'UP-SSC-Jail-Warder.pdf'
    },
    {
        id: '6',
        post_title: 'Rajasthan Police - Constable Recruitment 2024',
        post_name: 'Rajasthan Police Constable Online Form 2024',
        post_date: '20-11-2024',
        post_update: '20-11-2024',
        post_vacancy: '1500',
        post_information: 'Rajasthan Police has announced the recruitment of 1500 Constables. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 300/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 150/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 20-11-2024',
        post_imp2: 'Last Date for Apply Online: 20-12-2024',
        post_imp3: 'Candidates must have passed 12th Grade to apply.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 23 Years',
        pdf_filename: 'Rajasthan-Police-Constable.pdf'
    },
    {
        id: '7',
        post_title: 'Haryana SSC - Clerk Recruitment 2024',
        post_name: 'Haryana SSC Clerk Online Form 2024',
        post_date: '25-11-2024',
        post_update: '25-11-2024',
        post_vacancy: '700',
        post_information: 'Haryana Staff Selection Commission (HSSC) is recruiting 700 Clerks. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 200/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 25-11-2024',
        post_imp2: 'Last Date for Apply Online: 15-12-2024',
        post_imp3: 'Candidates must have passed 12th Grade to apply.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 42 Years',
        pdf_filename: 'Haryana-SSC-Clerk.pdf'
    },
    {
        id: '8',
        post_title: 'Territorial Army Soldier Recruitment 2024',
        post_name: 'Territorial Army Soldier Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '2847',
        post_information: 'The Territorial Army is recruiting 2847 Soldiers, Clerks, and other positions. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 200/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed at least 8th, 10th, or 10+2 to apply.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 42 Years',
        pdf_filename: 'Territorial-Army.pdf'
    },
    {
        id: '9',
        post_title: 'HSL Manager Recruitment 2024',
        post_name: 'HSL Manager Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '57',
        post_information: 'Hindustan Shipyard Limited (HSL) is recruiting 57 Managers, Senior Managers, and other roles. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 500/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 05-11-2024',
        post_imp3: 'Candidates must have CA, ICWA, Diploma, Degree, or PG in relevant disciplines to apply.',
        post_age1: 'Minimum Age Limit: 21 Years',
        post_age2: 'Maximum Age Limit: 45 Years',
        pdf_filename: 'HSL-Manager-Recruitment.pdf'
    },
    {
        id: '10',
        post_title: 'ITBP Assistant Sub-Inspector Recruitment 2024',
        post_name: 'ITBP Assistant Sub-Inspector Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '20',
        post_information: 'Indo-Tibetan Border Police (ITBP) is hiring 20 Assistant Sub-Inspectors and Head Constables. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 300/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 150/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 26-11-2024',
        post_imp3: 'Candidates must have completed 12th and possess a Diploma in relevant disciplines to apply.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 25 Years',
        pdf_filename: 'ITBP-Assistant-Sub-Inspector.pdf'
    },  
    {
        id: '11',
        post_title: 'Navy AA SSR Recruitment 2024',
        post_name: 'Navy AA SSR Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '300',
        post_information: 'Indian Navy is hiring 300 AA SSR candidates. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 12th with Physics, Chemistry, and Mathematics.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-AA-SSR.pdf'
    },
    {
        id: '12',
        post_title: 'Navy MR Recruitment 2024',
        post_name: 'Navy MR Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '400',
        post_information: 'Indian Navy is hiring 400 Matric Recruit candidates. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 10th grade.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-MR.pdf'
    },
    {
        id: '13',
        post_title: 'Navy AA SSR Technician Recruitment 2024',
        post_name: 'Navy AA SSR Technician Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '150',
        post_information: 'Indian Navy is hiring 150 AA SSR Technicians. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 12th with relevant vocational subjects.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-AA-SSR-Technician.pdf'
    },
    {
        id: '14',
        post_title: 'Navy MR Chef Recruitment 2024',
        post_name: 'Navy MR Chef Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '100',
        post_information: 'Indian Navy is hiring 100 Chef Matric Recruit candidates. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 10th grade.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-MR-Chef.pdf'
    },
    {
        id: '15',
        post_title: 'Navy MR Steward Recruitment 2024',
        post_name: 'Navy MR Steward Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '100',
        post_information: 'Indian Navy is hiring 100 Steward Matric Recruit candidates. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 10th grade.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-MR-Steward.pdf'
    },
    {
        id: '16',
        post_title: 'Navy MR Hygienist Recruitment 2024',
        post_name: 'Navy MR Hygienist Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '50',
        post_information: 'Indian Navy is hiring 50 Hygienist Matric Recruit candidates. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 10th grade.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-MR-Hygienist.pdf'
    },
    {
        id: '17',
        post_title: 'Navy AA SSR Electrical Recruitment 2024',
        post_name: 'Navy AA SSR Electrical Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '200',
        post_information: 'Indian Navy is hiring 200 AA SSR candidates in Electrical trades. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 12th with Physics and Mathematics.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-AA-SSR-Electrical.pdf'
    },
    {
        id: '18',
        post_title: 'Navy AA SSR Mechanical Recruitment 2024',
        post_name: 'Navy AA SSR Mechanical Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '250',
        post_information: 'Indian Navy is hiring 250 AA SSR candidates in Mechanical trades. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 12th with Physics and Mathematics.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-AA-SSR-Mechanical.pdf'
    },
    {
        id: '19',
        post_title: 'Navy AA SSR IT Recruitment 2024',
        post_name: 'Navy AA SSR IT Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '100',
        post_information: 'Indian Navy is hiring 100 AA SSR candidates in IT. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 12th with Computer Science.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-AA-SSR-IT.pdf'
    },
    {
        id: '20',
        post_title: 'Navy AA SSR Electronics Recruitment 2024',
        post_name: 'Navy AA SSR Electronics Online Form 2024',
        post_date: '01-11-2024',
        post_update: '01-11-2024',
        post_vacancy: '150',
        post_information: 'Indian Navy is hiring 150 AA SSR candidates in Electronics. Candidates can read the Notification & Apply Online.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-11-2024',
        post_imp2: 'Last Date for Apply Online: 30-11-2024',
        post_imp3: 'Candidates must have completed 12th with Physics and Mathematics.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 20 Years',
        pdf_filename: 'Navy-AA-SSR-Electronics.pdf'
    },
    {
        id: '21',
        post_title: 'Indian Air Force Agniveer Vayu Recruitment 2024',
        post_name: 'Agniveer Vayu Online Form 2024',
        post_date: '01-12-2024',
        post_update: '01-12-2024',
        post_vacancy: 'Various',
        post_information: 'Indian Air Force is hiring Agniveer Vayu candidates for various trades. Candidates must have completed 12th with Physics, Mathematics, and English.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-12-2024',
        post_imp2: 'Last Date for Apply Online: 31-12-2024',
        post_imp3: 'Candidates must have completed 12th with Physics, Mathematics, and English.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 21 Years',
        pdf_filename: 'IAF-Agniveer-Vayu.pdf'
    },
    {
        id: '22',
        post_title: 'Indian Air Force Group X Recruitment 2024',
        post_name: 'Group X Online Form 2024',
        post_date: '01-12-2024',
        post_update: '01-12-2024',
        post_vacancy: 'Various',
        post_information: 'Indian Air Force is hiring for Group X trades. Candidates must have completed 12th with Mathematics, Physics, and English with a minimum of 50% marks.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-12-2024',
        post_imp2: 'Last Date for Apply Online: 31-12-2024',
        post_imp3: 'Candidates must have completed 12th with Mathematics, Physics, and English with a minimum of 50% marks.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 21 Years',
        pdf_filename: 'IAF-Group-X.pdf'
    },
    {
        id: '23',
        post_title: 'Indian Air Force Group Y Recruitment 2024',
        post_name: 'Group Y Online Form 2024',
        post_date: '01-12-2024',
        post_update: '01-12-2024',
        post_vacancy: 'Various',
        post_information: 'Indian Air Force is hiring for Group Y trades. Candidates must have completed 12th with any stream.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 250/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 100/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-12-2024',
        post_imp2: 'Last Date for Apply Online: 31-12-2024',
        post_imp3: 'Candidates must have completed 12th with any stream.',
        post_age1: 'Minimum Age Limit: 17 Years',
        post_age2: 'Maximum Age Limit: 21 Years',
        pdf_filename: 'IAF-Group-Y.pdf'
    },
    {
        id: '24',
        post_title: 'Indian Air Force Medical Branch Recruitment 2024',
        post_name: 'Medical Branch Online Form 2024',
        post_date: '01-12-2024',
        post_update: '01-12-2024',
        post_vacancy: 'Various',
        post_information: 'Indian Air Force is hiring candidates for the Medical Branch. Candidates must have completed MBBS.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 500/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 200/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-12-2024',
        post_imp2: 'Last Date for Apply Online: 15-01-2025',
        post_imp3: 'Candidates must have completed MBBS.',
        post_age1: 'Minimum Age Limit: 20 Years',
        post_age2: 'Maximum Age Limit: 30 Years',
        pdf_filename: 'IAF-Medical-Branch.pdf'
    },
    {
        id: '25',
        post_title: 'Indian Air Force Engineering Branch Recruitment 2024',
        post_name: 'Engineering Branch Online Form 2024',
        post_date: '01-12-2024',
        post_update: '01-12-2024',
        post_vacancy: 'Various',
        post_information: 'Indian Air Force is hiring candidates for the Engineering Branch. Candidates must have completed a B.Tech or BE in relevant fields.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 500/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 200/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-12-2024',
        post_imp2: 'Last Date for Apply Online: 15-01-2025',
        post_imp3: 'Candidates must have completed a B.Tech or BE in relevant fields.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 28 Years',
        pdf_filename: 'IAF-Engineering-Branch.pdf'
    },
    {
        id: '26',
        post_title: 'Indian Air Force Logistics Branch Recruitment 2024',
        post_name: 'Logistics Branch Online Form 2024',
        post_date: '01-12-2024',
        post_update: '01-12-2024',
        post_vacancy: 'Various',
        post_information: 'Indian Air Force is hiring for the Logistics Branch. Candidates must have completed a Bachelor\'s degree in any discipline.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 500/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 200/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-12-2024',
        post_imp2: 'Last Date for Apply Online: 15-01-2025',
        post_imp3: 'Candidates must have completed a Bachelor\'s degree in any discipline.',
        post_age1: 'Minimum Age Limit: 18 Years',
        post_age2: 'Maximum Age Limit: 28 Years',
        pdf_filename: 'IAF-Logistics-Branch.pdf'
    },
    {
        id: '27',
        post_title: 'Indian Air Force Education Branch Recruitment 2024',
        post_name: 'Education Branch Online Form 2024',
        post_date: '01-12-2024',
        post_update: '01-12-2024',
        post_vacancy: 'Various',
        post_information: 'Indian Air Force is hiring for the Education Branch. Candidates must have completed a Master\'s degree in relevant subjects.',
        post_application1: 'For General, EWS & OBC Candidates: Rs. 500/- + Applicable Taxes + Payment Gateway charges',
        post_application2: 'For SC/ ST/ PWD Candidates: Rs. 200/- + Applicable Taxes + Payment Gateway charges',
        post_application3: 'Payment Mode: Through Online',
        post_imp1: 'Starting Date for Apply Online: 01-12-2024',
        post_imp2: 'Last Date for Apply Online: 15-01-2025',
        post_imp3: 'Candidates must have completed a Master\'s degree in relevant subjects.',
        post_age1: 'Minimum Age Limit: 20 Years',
        post_age2: 'Maximum Age Limit: 30 Years',
        pdf_filename: 'IAF-Education-Branch.pdf'
    },
    {
        id: '28',
       post_title: "Tentative Exam Calendar 2024-25",
        post_name: "IBPS Tentative Exam Calendar 2024-25",
        post_date: "18-01-2024",
        post_update: "18-01-2024",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "Institute of Banking Personnel Selection (IBPS) has released the tentative exam calendar for the year 2024-25. The calendar includes the schedule for various exams, including Probationary Officers (PO), Clerks, and Specialist Officers (SO) recruitment. Candidates interested in banking sector jobs can check the tentative dates and start preparing accordingly.",
        post_application1: "Application fees will vary for different posts and categories.",
        post_application2: "Exact fee details to be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: Tentative dates will be released with specific exam notifications.",
        post_imp2: "Tentative Exam Dates: Various exams will be held between August 2024 to January 2025",
        post_imp3: "Final deadlines and updates will be announced with respective exam notifications.",
        post_age1: "Minimum Age Limit: Varies based on the position (PO/Clerk/SO) – Typically 20 Years",
        post_age2: "Maximum Age Limit: Varies based on the position (PO/Clerk/SO) – Typically 30 Years",
        pdf_filename: "IBPS-Exam-Calendar-2024-25.pdf"
    },
    {
        id: '29',
        post_title: "Exam Calendar 2023",
        post_name: "IBPS Exam Calendar 2023",
        post_date: "19-01-2023",
        post_update: "19-01-2023",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "Institute of Banking Personnel Selection (IBPS) has released the exam calendar for the year 2023. The calendar outlines the schedule for various exams, including Probationary Officers (PO), Clerks, and Specialist Officers (SO) recruitment. Candidates interested in banking jobs can check the exam dates and start preparing for their preferred posts accordingly.",
        post_application1: "Application fees will vary for different posts and categories.",
        post_application2: "Exact fee details to be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: Tentative dates will be released with specific exam notifications.",
        post_imp2: "Tentative Exam Dates: Various exams will be held between August 2023 to January 2024",
        post_imp3: "Final deadlines and updates will be announced with respective exam notifications.",
        post_age1: "Minimum Age Limit: Varies based on the position (PO/Clerk/SO) – Typically 20 Years",
        post_age2: "Maximum Age Limit: Varies based on the position (PO/Clerk/SO) – Typically 30 Years",
        pdf_filename: "IBPS-Exam-Calendar-2023.pdf"
    },  
    {
        id: '30',
        post_title: "RJ Central Cooperative Bank Assistant Recruitment 2022",
        post_name: "RJ Central Cooperative Bank Assistant Online Form 2022",
        post_date: "20-05-2022",
        post_update: "20-05-2022",
        post_vacancy: "440 Assistant Vacancies",
        post_information: "Rajasthan Central Cooperative Bank has announced the recruitment of 440 Assistant vacancies. Interested candidates who fulfill the eligibility criteria can apply online. This is a great opportunity for candidates looking to work in the cooperative banking sector in Rajasthan.",
        post_application1: "For General, OBC Candidates: Rs. 500/- + Applicable Taxes",
        post_application2: "For SC/ ST/ PWD Candidates: Rs. 250/- + Applicable Taxes",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: 01-04-2022",
        post_imp2: "Last Date for Apply Online: 20-05-2022",
        post_imp3: "Tentative Date for Exam: June 2022",
        post_age1: "Minimum Age Limit: 21 Years",
        post_age2: "Maximum Age Limit: 35 Years",
        pdf_filename: "RJ-Central-Cooperative-Bank-2022.pdf"
    },
    {
        id: '30',
        post_title: "RJ Central Cooperative Bank Assistant Recruitment 2022",
        post_name: "RJ Central Cooperative Bank Assistant Online Form 2022",
        post_date: "20-05-2022",
        post_update: "20-05-2022",
        post_vacancy: "440 Assistant Vacancies",
        post_information: "Rajasthan Central Cooperative Bank has announced the recruitment of 440 Assistant vacancies. Interested candidates who fulfill the eligibility criteria can apply online. This is a great opportunity for candidates looking to work in the cooperative banking sector in Rajasthan.",
        post_application1: "For General, OBC Candidates: Rs. 500/- + Applicable Taxes",
        post_application2: "For SC/ ST/ PWD Candidates: Rs. 250/- + Applicable Taxes",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: 01-04-2022",
        post_imp2: "Last Date for Apply Online: 20-05-2022",
        post_imp3: "Tentative Date for Exam: June 2022",
        post_age1: "Minimum Age Limit: 21 Years",
        post_age2: "Maximum Age Limit: 35 Years",
        pdf_filename: "RJ-Central-Cooperative-Bank-2022.pdf"
    },
    {
        id: '32',
        post_title: "IBPS SO XII Recruitment 2022",
        post_name: "IBPS Specialist Officer XII Online Form 2022",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Specialist Officer XII Vacancies (Exact Number TBA)",
        post_information: "The Institute of Banking Personnel Selection (IBPS) has released the notification for the recruitment of Specialist Officer XII positions. Candidates interested in specialist roles like IT, HR, Marketing, Law, Agriculture, etc., can apply online.",
        post_application1: "For General, OBC Candidates: Rs. 850/- + Applicable Taxes",
        post_application2: "For SC/ ST/ PWD Candidates: Rs. 175/- + Applicable Taxes",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: 01-03-2022",
        post_imp2: "Last Date for Apply Online: 14-03-2022",
        post_imp3: "Tentative Exam Dates: July 2022 (Preliminary), September 2022 (Mains)",
        post_age1: "Minimum Age Limit: 20 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "IBPS-SO-XII-2022.pdf"
    },
    {
        id: '33',
        post_title: "IBPS PO/MT XII Recruitment 2022",
        post_name: "IBPS Probationary Officers/Management Trainees XII Online Form 2022",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Probationary Officers/Management Trainees XII Vacancies (Exact Number TBA)",
        post_information: "The Institute of Banking Personnel Selection (IBPS) has released the notification for the recruitment of Probationary Officers/Management Trainees XII positions. Candidates interested in management trainee roles in public sector banks can apply online.",
        post_application1: "For General, OBC Candidates: Rs. 850/- + Applicable Taxes",
        post_application2: "For SC/ ST/ PWD Candidates: Rs. 175/- + Applicable Taxes",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: 01-03-2022",
        post_imp2: "Last Date for Apply Online: 14-03-2022",
        post_imp3: "Tentative Exam Dates: July 2022 (Preliminary), September 2022 (Mains)",
        post_age1: "Minimum Age Limit: 20 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "IBPS-PO-MT-XII-2022.pdf"
    },
    {
        id: '34',
        post_title: "IBPS Exam Calendar 2022-23",
        post_name: "IBPS Exam Calendar 2022-23",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "Institute of Banking Personnel Selection (IBPS) has released the exam calendar for 2022-23. The calendar outlines the dates for various recruitment exams, including PO, Clerk, and SO posts.",
        post_application1: "Application fees will vary for different posts and categories.",
        post_application2: "Exact fee details to be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: Tentative dates will be released with specific exam notifications.",
        post_imp2: "Tentative Exam Dates: Various exams will be held between August 2022 to January 2023",
        post_imp3: "Final deadlines and updates will be announced with respective exam notifications.",
        post_age1: "Minimum Age Limit: Varies based on the position (PO/Clerk/SO) – Typically 20 Years",
        post_age2: "Maximum Age Limit: Varies based on the position (PO/Clerk/SO) – Typically 30 Years",
        pdf_filename: "IBPS-Exam-Calendar-2022-23.pdf"
    },
    {
        id: '35',
        post_title: "IBPS Tentative Exam Calendar 2021-22",
        post_name: "IBPS Tentative Exam Calendar 2021-22",
        post_date: "03-02-2021",
        post_update: "03-02-2021",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "Institute of Banking Personnel Selection (IBPS) has released the tentative exam calendar for the year 2021-22. The calendar includes the schedule for various exams, including PO, Clerk, and SO recruitment.",
        post_application1: "Application fees will vary for different posts and categories.",
        post_application2: "Exact fee details to be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: Tentative dates will be released with specific exam notifications.",
        post_imp2: "Tentative Exam Dates: Various exams will be held between August 2021 to January 2022",
        post_imp3: "Final deadlines and updates will be announced with respective exam notifications.",
        post_age1: "Minimum Age Limit: Varies based on the position (PO/Clerk/SO) – Typically 20 Years",
        post_age2: "Maximum Age Limit: Varies based on the position (PO/Clerk/SO) – Typically 30 Years",
        pdf_filename: "IBPS-Exam-Calendar-2021-22.pdf"
    },
    {
        id: '36',
        post_title: "RRB NTPC Recruitment 2024",
        post_name: "RRB NTPC Tentative Vacancies 2024",
        post_date: "01-08-2024",
        post_update: "01-08-2024",
        post_vacancy: "Tentative Vacancies for NTPC (Exact Number TBA)",
        post_information: "The Railway Recruitment Board (RRB) is expected to release the notification for the Non-Technical Popular Categories (NTPC) recruitment for 2024. Interested candidates can check the tentative vacancy details and start preparing for the upcoming exams.",
        post_application1: "Application fees for General, OBC: Rs. 500/- + Applicable Taxes",
        post_application2: "For SC/ST/PWD Candidates: Rs. 250/- + Applicable Taxes",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: To be announced with official notification.",
        post_imp2: "Tentative Exam Date: Expected in late 2024.",
        post_imp3: "Final exam schedule will be confirmed in the official notification.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "RRB-NTPC-2024.pdf"
    },
    {
        id: '37',
        post_title: "RRB Annual Planner 2024",
        post_name: "RRB Annual Planner 2024",
        post_date: "19-04-2024",
        post_update: "19-04-2024",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "The Railway Recruitment Board (RRB) has released the annual planner for 2024. This planner contains tentative dates and recruitment details for various posts across different railway departments. Candidates interested in railway jobs can use this as a guide for upcoming exams and notifications.",
        post_application1: "Application fees will vary depending on the post and category.",
        post_application2: "Exact fee details will be available in respective exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: Will be released with specific notifications.",
        post_imp2: "Tentative Exam Dates: Throughout 2024",
        post_imp3: "Updates on deadlines and exam schedules will be announced with individual notifications.",
        post_age1: "Minimum Age Limit: Varies by position (typically 18 years).",
        post_age2: "Maximum Age Limit: Varies by position (typically 30 years).",
        pdf_filename: "RRB-Annual-Planner-2024.pdf"
    },
    {
        id: '38',
        post_title: "RRB NTPC Exam News 2024",
        post_name: "RRB NTPC Exam News 2024",
        post_date: "19-04-2024",
        post_update: "19-04-2024",
        post_vacancy: "Information on NTPC Exam (Vacancies TBA)",
        post_information: "Railway Recruitment Board (RRB) has provided updates on the NTPC exams for 2024. Candidates preparing for Non-Technical Popular Categories exams can check this news update for important dates, syllabus details, and changes to the exam format.",
        post_application1: "General, OBC Candidates: Rs. 500/- + Applicable Taxes",
        post_application2: "For SC/ST/PWD Candidates: Rs. 250/- + Applicable Taxes",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Online Registration Date: To be announced soon.",
        post_imp2: "Tentative Exam Date: Late 2024",
        post_imp3: "Official notification will provide final details on the exam schedule.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "RRB-NTPC-Exam-News-2024.pdf"
    },
    {
        id: '39',
        post_title: "RRB Annual Calendar 2024",
        post_name: "RRB Annual Calendar 2024",
        post_date: "05-02-2024",
        post_update: "05-02-2024",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "The Railway Recruitment Board (RRB) has released the annual calendar for the year 2024. It includes the tentative dates for various recruitment exams across different railway departments. Candidates interested in railway jobs should check this calendar to stay updated on upcoming opportunities.",
        post_application1: "Application fees will be updated with specific notifications.",
        post_application2: "Different fees may apply for different posts and categories.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: Will be announced with individual notifications.",
        post_imp2: "Tentative Exam Dates: Scheduled throughout 2024.",
        post_imp3: "Further details will be available in the specific job notifications.",
        post_age1: "Minimum Age Limit: Typically 18 Years",
        post_age2: "Maximum Age Limit: Typically 30 Years",
        pdf_filename: "RRB-Annual-Calendar-2024.pdf"
    },
    {
        id: '40',
        post_title: "Indian Railways Vacancy Information 2023",
        post_name: "Indian Railways Vacancies 2023",
        post_date: "07-02-2023",
        post_update: "07-02-2023",
        post_vacancy: "Various Posts in Indian Railways (Exact Vacancies TBA)",
        post_information: "Indian Railways has provided updated information regarding upcoming vacancies for 2023. This includes details on multiple recruitment exams that will be conducted throughout the year for various technical and non-technical posts.",
        post_application1: "Application fees will be updated with the specific post notifications.",
        post_application2: "Candidates are advised to check official notices for fee details.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: Dates to be announced in notifications.",
        post_imp2: "Tentative Exam Dates: Various dates in 2023.",
        post_imp3: "Official notifications will provide further updates.",
        post_age1: "Minimum Age Limit: Typically 18 Years",
        post_age2: "Maximum Age Limit: Typically 30 Years",
        pdf_filename: "Indian-Railways-Vacancy-Info-2023.pdf"
    },
    {
        id: '41',
        post_title: "RPF Constable/SI Recruitment 2022",
        post_name: "RPF Constable, Sub-Inspector 2022 Online Form",
        post_date: "20-05-2022",
        post_update: "20-05-2022",
        post_vacancy: "9000 Vacancies (Constable and SI)",
        post_information: "Railway Protection Force (RPF) has released a notification for the recruitment of 9000 Constables and Sub-Inspectors. This is a great opportunity for candidates looking to serve in the railway protection force. Eligible candidates can apply online before the deadline.",
        post_application1: "For General, OBC Candidates: Rs. 500/- + Applicable Taxes",
        post_application2: "For SC/ST/PWD Candidates: Rs. 250/- + Applicable Taxes",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: 01-03-2022",
        post_imp2: "Last Date for Apply Online: 20-05-2022",
        post_imp3: "Tentative Exam Date: July 2022",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "RPF-Constable-SI-2022.pdf"
    },
    {
        id: '42',
        post_title: "BSF Constable (Tradesman) Notification 2024",
        post_name: "BSF Constable Tradesman Notification 2024",
        post_date: "04-01-2024",
        post_update: "04-01-2024",
        post_vacancy: "Constable (Tradesman) – Exact Vacancies TBA",
        post_information: "The Border Security Force (BSF) has released the notification for the recruitment of Constables (Tradesman) for 2024. Interested candidates can check the eligibility criteria and important dates to apply for the position.",
        post_application1: "General, OBC Candidates: Rs. 100/- + Applicable Taxes",
        post_application2: "SC/ST/Female Candidates: No Application Fees",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: To be announced with official notification.",
        post_imp2: "Tentative Exam Date: March 2024.",
        post_imp3: "Further details will be provided in the official notification.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 25 Years",
        pdf_filename: "BSF-Constable-Tradesman-2024.pdf"
    },
    {
        id: '43',
        post_title: "Ordinance Factory Vacancy Details 2023",
        post_name: "Ordinance Factory Vacancy 2023",
        post_date: "02-01-2024",
        post_update: "02-01-2024",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "Ordinance Factory has released new vacancy details for 2023. Interested candidates can apply for various technical and non-technical posts. The detailed notification will be available on the official website.",
        post_application1: "General, OBC Candidates: Rs. 200/- + Applicable Taxes",
        post_application2: "SC/ST/PWD Candidates: No Fees",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: Will be updated with official notification.",
        post_imp2: "Tentative Exam Date: To be announced in 2024.",
        post_imp3: "Final exam schedule and deadlines will be updated soon.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "Ordinance-Factory-Vacancy-2023.pdf"
    },
    {
        id: '44',
        post_title: "CAG Various Vacancy Details 2023",
        post_name: "CAG Vacancy Notification 2023",
        post_date: "02-01-2024",
        post_update: "02-01-2024",
        post_vacancy: "Various Posts in CAG (Exact Vacancies TBA)",
        post_information: "The Comptroller and Auditor General (CAG) of India has released a notification for various vacancies in 2023. Interested candidates can apply for the relevant posts by following the eligibility criteria provided in the official notification.",
        post_application1: "General, OBC Candidates: Rs. 200/- + Applicable Taxes",
        post_application2: "SC/ST/PWD Candidates: No Fees",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: To be announced soon.",
        post_imp2: "Tentative Exam Date: In 2024.",
        post_imp3: "Further details will be available in the official notification.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "CAG-Vacancy-Details-2023.pdf"
    },
    {
        id: '45',
        post_title: "CRPF Constable Recruitment 2023",
        post_name: "CRPF Constable 129929 Vacancies 2023",
        post_date: "08-04-2023",
        post_update: "08-04-2023",
        post_vacancy: "129929 Constable Vacancies",
        post_information: "The Central Reserve Police Force (CRPF) has announced a massive recruitment drive for 129,929 constable positions in 2023. Interested candidates are encouraged to apply for this opportunity before the deadline.",
        post_application1: "General, OBC Candidates: Rs. 100/- + Applicable Taxes",
        post_application2: "SC/ST/PWD Candidates: No Application Fee",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: 01-04-2023",
        post_imp2: "Last Date to Apply Online: 08-04-2023",
        post_imp3: "Tentative Exam Date: July 2023",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "CRPF-Constable-129929-Vacancies-2023.pdf"
    },
    {
        id: '46',
        post_title: "DRDO-SAC Notification Through GATE 2023",
        post_name: "DRDO-SAC Recruitment Through GATE 2023",
        post_date: "29-09-2022",
        post_update: "29-09-2022",
        post_vacancy: "Various Scientist/Engineer Positions",
        post_information: "Defense Research and Development Organization (DRDO) and Space Applications Centre (SAC) are recruiting through GATE 2023. Candidates with a valid GATE score can apply for Scientist/Engineer positions in DRDO-SAC.",
        post_application1: "General, OBC Candidates: Rs. 100/- + Applicable Taxes",
        post_application2: "SC/ST/PWD Candidates: No Application Fee",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: 15-09-2022",
        post_imp2: "Last Date to Apply Online: 29-09-2022",
        post_imp3: "Tentative Exam Date: December 2022",
        post_age1: "Minimum Age Limit: 21 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "DRDO-SAC-GATE-2023.pdf"
    },
    {
        id: '47',
        post_title: "Army Ordinance Corps Civilian Vacancy 2022",
        post_name: "Army Ordinance Corps Civilian Recruitment 2022",
        post_date: "29-08-2022",
        post_update: "29-08-2022",
        post_vacancy: "Various Civilian Positions",
        post_information: "The Army Ordinance Corps has announced a recruitment drive for various civilian positions in 2022. Eligible candidates can apply online for these vacancies before the deadline.",
        post_application1: "General, OBC Candidates: Rs. 200/- + Applicable Taxes",
        post_application2: "SC/ST Candidates: No Fees",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: 01-08-2022",
        post_imp2: "Last Date to Apply Online: 29-08-2022",
        post_imp3: "Tentative Exam Date: October 2022",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "Army-Ordinance-Corps-Civilian-2022.pdf"
    },
    {
        id: '48',
        post_title: "Territorial Army Vacancy Notification 2022",
        post_name: "Territorial Army Various Vacancy Notification 2022",
        post_date: "13-06-2022",
        post_update: "13-06-2022",
        post_vacancy: "Various Vacancies in Territorial Army",
        post_information: "The Territorial Army has released a notification for various vacancies in 2022. Interested candidates can apply online for different positions in the Territorial Army before the deadline.",
        post_application1: "General, OBC Candidates: Rs. 200/- + Applicable Taxes",
        post_application2: "SC/ST/PWD Candidates: No Fees",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: 01-06-2022",
        post_imp2: "Last Date to Apply Online: 13-06-2022",
        post_imp3: "Tentative Exam Date: August 2022",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 35 Years",
        pdf_filename: "Territorial-Army-Vacancy-2022.pdf"
    },
    {
        id: '49',
        post_title: "SSC Constable 2024 Notification",
        post_name: "SSC Constable Notification 2024",
        post_date: "28-08-2024",
        post_update: "28-08-2024",
        post_vacancy: "Various Constable Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission (SSC) has released the notification for the recruitment of Constables for the year 2024. Interested candidates are encouraged to apply and check the eligibility criteria.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: To be announced with official notification.",
        post_imp2: "Tentative Exam Date: September 2024.",
        post_imp3: "Final deadlines and updates will be announced with respective exam notifications.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 25 Years",
        pdf_filename: "SSC-Constable-2024-Notification.pdf"
    },
    {
        id: '50',
        post_title: "SSC Revised Exam Calendar 2024-25",
        post_name: "SSC Revised Exam Calendar 2024-25",
        post_date: "18-06-2024",
        post_update: "18-06-2024",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released a revised exam calendar for 2024-25. Candidates can check the tentative dates for various examinations scheduled for the year.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Revised Exam Dates: Various exams scheduled in 2024-25.",
        post_imp2: "Candidates should regularly check for updates.",
        post_imp3: "Final exam schedule will be provided in official notifications.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Revised-Exam-Calendar-2024-25.pdf"
    },
    {
        id: '51',
        post_title: "SSC Exam Calendar 2024-25",
        post_name: "SSC Exam Calendar 2024-25",
        post_date: "30-12-2023",
        post_update: "30-12-2023",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released the exam calendar for the year 2024-25. This calendar includes important dates for various recruitment examinations.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Starting Date for Online Registration: To be announced with official notification.",
        post_imp2: "Tentative Exam Dates: Various exams scheduled for 2024-25.",
        post_imp3: "Final exam schedule will be provided in official notifications.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Exam-Calendar-2024-25.pdf"
    },
    {
        id: '52',
        post_title: "SSC Tentative Calendar of Exams for 2024-25",
        post_name: "SSC Tentative Calendar 2024-25",
        post_date: "16-11-2023",
        post_update: "16-11-2023",
        post_vacancy: "Various Exams (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released the tentative calendar for exams scheduled in 2024-25. Candidates can start preparing based on these tentative dates.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Tentative Exam Dates: Various exams scheduled for 2024-25.",
        post_imp2: "Candidates are advised to keep checking for updates.",
        post_imp3: "Final exam dates will be announced in official notifications.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Tentative-Calendar-2024-25.pdf"
    },
    {
        id: '53',
        post_title: "SSC Tentative Calendar of Exams for 2023-24",
        post_name: "SSC Tentative Calendar 2023-24",
        post_date: "11-09-2023",
        post_update: "11-09-2023",
        post_vacancy: "Various Exams (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released the tentative calendar for exams scheduled in 2023-24. Candidates should refer to these dates for their preparation.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Tentative Exam Dates: Various exams scheduled for 2023-24.",
        post_imp2: "Updates will be provided in official notifications.",
        post_imp3: "Candidates should keep checking for updates.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Tentative-Calendar-2023-24.pdf"
    },
    {
        id: '54',
        post_title: "SSC Revised Annual Planner Calendar",
        post_name: "SSC Revised Annual Planner 2023",
        post_date: "09-06-2023",
        post_update: "09-06-2023",
        post_vacancy: "Various Exams (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released a revised annual planner for various exams. Candidates are advised to check the details for accurate exam dates.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Tentative Exam Dates: To be confirmed in official notifications.",
        post_imp2: "Candidates should stay updated for the latest information.",
        post_imp3: "Final exam schedule will be available in official notifications.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Revised-Annual-Planner-2023.pdf"
    },
    {
        id: '55',
        post_title: "SSC Exam Schedule",
        post_name: "SSC Exam Schedule 2023",
        post_date: "22-05-2023",
        post_update: "22-05-2023",
        post_vacancy: "Various Exams (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released the exam schedule for various exams. Candidates can refer to this schedule for important dates.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Tentative Exam Dates: Various exams scheduled for 2023.",
        post_imp2: "Candidates should refer to the official site for updates.",
        post_imp3: "Final exam schedule will be confirmed in official notifications.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Exam-Schedule-2023.pdf"
    },
    {
        id: '56',
        post_title: "SSC Various Exam Calendar in August, September & October 2023",
        post_name: "SSC Various Exam Calendar 2023",
        post_date: "02-05-2023",
        post_update: "02-05-2023",
        post_vacancy: "Various Exams (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released the exam calendar for various examinations taking place in August, September, and October 2023.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Tentative Exam Dates: Various exams scheduled in 2023.",
        post_imp2: "Candidates should regularly check for updates.",
        post_imp3: "Final exam dates will be provided in official notifications.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Various-Exam-Calendar-2023.pdf"
    },
    {
        id: '57',
        post_title: "SSC Tentative Annual Calendar 2023-24",
        post_name: "SSC Tentative Annual Calendar 2023-24",
        post_date: "02-01-2023",
        post_update: "02-01-2023",
        post_vacancy: "Various Exams (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released a tentative annual calendar for exams in 2023-24. Candidates can refer to this calendar for important dates.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Tentative Exam Dates: Various exams scheduled for 2023-24.",
        post_imp2: "Candidates are advised to check regularly for updates.",
        post_imp3: "Final exam dates will be confirmed in official notifications.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Tentative-Annual-Calendar-2023-24.pdf"
    },
    {
        id: '58',
        post_title: "SSC CHSL Exam 2022",
        post_name: "SSC CHSL Exam 2022",
        post_date: "04-11-2022",
        post_update: "04-11-2022",
        post_vacancy: "Various CHSL Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has conducted the CHSL Exam 2022. Results and further information will be announced soon.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Date: November 2022.",
        post_imp2: "Results will be announced post-exam.",
        post_imp3: "Updates will be provided on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-CHSL-Exam-2022.pdf"
    },
    {
        id: '59',
        post_title: "SSC Exam Calendar 2022-23",
        post_name: "SSC Exam Calendar 2022-23",
        post_date: "06-07-2022",
        post_update: "06-07-2022",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released the exam calendar for the year 2022-23. Candidates can refer to this calendar for important exam dates.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Dates: Various exams scheduled for 2022-23.",
        post_imp2: "Updates will be provided in official notifications.",
        post_imp3: "Final exam schedule will be available on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Exam-Calendar-2022-23.pdf"
    },
    {
        id: '60',
        post_title: "SSC Going to fill 70,000 Vacancies Soon",
        post_name: "SSC 70,000 Vacancies Update",
        post_date: "23-06-2022",
        post_update: "23-06-2022",
        post_vacancy: "70,000 Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has announced plans to fill 70,000 vacancies soon. Candidates are advised to stay tuned for further updates.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Vacancies: 70,000 posts will be filled.",
        post_imp2: "Further details will be shared soon.",
        post_imp3: "Candidates should keep checking the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-70000-Vacancies-Update.pdf"
    },
    {
        id: '61',
        post_title: "SSC Stenographer 2021",
        post_name: "SSC Stenographer 2021",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Various Stenographer Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has conducted the Stenographer Exam for 2021. Results and further updates will be announced soon.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Date: March 2022.",
        post_imp2: "Results will be announced post-exam.",
        post_imp3: "Updates will be provided on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Stenographer-2021.pdf"
    },
    {
        id: '62',
        post_title: "SSC Jr Engineer 2021",
        post_name: "SSC Jr Engineer 2021",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Various Jr Engineer Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has conducted the Jr Engineer Exam for 2021. Results and further updates will be announced soon.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Date: March 2022.",
        post_imp2: "Results will be announced post-exam.",
        post_imp3: "Updates will be provided on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Jr-Engineer-2021.pdf"
    },
    {
        id: '63',
        post_title: "SSC SI & CAPF Exam 2021",
        post_name: "SSC SI & CAPF Exam 2021",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Various SI & CAPF Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has conducted the SI & CAPF Exam for 2021. Results and further updates will be announced soon.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Date: March 2022.",
        post_imp2: "Results will be announced post-exam.",
        post_imp3: "Updates will be provided on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-SI-CAPF-Exam-2021.pdf"
    },
    {
        id: '64',
        post_title: "SSC Constable Driver 2022",
        post_name: "SSC Constable Driver 2022",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Various Constable Driver Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has conducted the Constable Driver Exam for 2022. Results and further updates will be announced soon.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Date: March 2022.",
        post_imp2: "Results will be announced post-exam.",
        post_imp3: "Updates will be provided on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Constable-Driver-2022.pdf"
    },
    {
        id: '65',
        post_title: "SSC Constable GD 2022",
        post_name: "SSC Constable GD 2022",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Various Constable GD Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has conducted the Constable GD Exam for 2022. Results and further updates will be announced soon.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Date: March 2022.",
        post_imp2: "Results will be announced post-exam.",
        post_imp3: "Updates will be provided on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Constable-GD-2022.pdf"
    },
    {
        id: '66',
        post_title: "SSC Head Constable AWO 2022",
        post_name: "SSC Head Constable AWO 2022",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Various Head Constable AWO Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has conducted the Head Constable AWO Exam for 2022. Results and further updates will be announced soon.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Date: March 2022.",
        post_imp2: "Results will be announced post-exam.",
        post_imp3: "Updates will be provided on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Head-Constable-AWO-2022.pdf"
    },
    {
        id: '67',
        post_title: "SSC Exam Calendar 2022-23",
        post_name: "SSC Exam Calendar 2022-23",
        post_date: "14-03-2022",
        post_update: "14-03-2022",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released the exam calendar for the year 2022-23. Candidates can refer to this calendar for important exam dates.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Dates: Various exams scheduled for 2022-23.",
        post_imp2: "Updates will be provided in official notifications.",
        post_imp3: "Final exam schedule will be available on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Exam-Calendar-2022-23.pdf"
    },
    {
        id: '68',
        post_title: "SSC Exam Calendar 2021-22",
        post_name: "SSC Exam Calendar 2021-22",
        post_date: "17-12-2021",
        post_update: "17-12-2021",
        post_vacancy: "Various Posts (Exact Vacancies TBA)",
        post_information: "The Staff Selection Commission has released the exam calendar for the year 2021-22. Candidates can refer to this calendar for important exam dates.",
        post_application1: "Application fees will vary based on the post and category.",
        post_application2: "Exact fee details will be updated with specific exam notifications.",
        post_application3: "Payment Mode: Through Online",
        post_imp1: "Exam Dates: Various exams scheduled for 2021-22.",
        post_imp2: "Updates will be provided in official notifications.",
        post_imp3: "Final exam schedule will be available on the official site.",
        post_age1: "Minimum Age Limit: 18 Years",
        post_age2: "Maximum Age Limit: 30 Years",
        pdf_filename: "SSC-Exam-Calendar-2021-22.pdf"
    }                                                         
]