export const Airforce_eligibility=[
    {
        exam: "Indian Air Force Airmen (Group Y - Non-Technical Tradesmen)",
        agelimit: "17-21 years",
        eligibility: "10th pass from a recognized board",
        AdditionalRequirements: "Physical fitness test (PFT), medical examination, and written test",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "Indian Air Force Airmen (Musician Trade)",
        agelimit:"17-25 years",
        eligibility: "10th pass from a recognized board",
        AdditionalRequirements: "Practical proficiency test in playing musical instruments, physical fitness test (PFT), and medical examination",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "Indian Air Force Airmen (Group Y - Security Trades)",
        agelimit: "17-21 years",
        eligibility: "10th pass with at least 50% marks in aggregate",
        AdditionalRequirements: "Physical fitness test (PFT), medical exam, and written test",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "Indian Air Force (Cook Trade)",
        agelimit: "17-25 years",
        eligibility: "10th pass from a recognized board",
        AdditionalRequirements: "Trade-specific skill test, physical fitness test (PFT), and medical examination",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "Indian Air Force (Ground Training Instructor)",
        agelimit: "17-25 years",
        eligibility: "10th pass from a recognized board",
        AdditionalRequirements: "Physical fitness test (PFT), instructional aptitude test, and medical examination",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "Indian Air Force Airmen (Group X - Technical)",
        agelimit: "17-21 years",
        eligibility: "12th pass with Physics, Chemistry, and Maths, with 50% marks in aggregate and 50% marks in English",
        AdditionalRequirements: "Physical fitness test (PFT), medical examination, and written test",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "Indian Air Force Airmen (Group Y - Non-Technical)",
        agelimit: "17-21 years",
        eligibility: "12th pass in any stream with 50% marks in aggregate and 50% marks in English",
        AdditionalRequirements: "Physical fitness test (PFT), medical examination, and written test",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "Indian Air Force Airmen (Group Y - Medical Assistant Trade)",
        agelimit: "17-21 years",
        eligibility: "12th pass with Physics, Chemistry, Biology, and English with 50% marks in aggregate and 50% marks in English",
        AdditionalRequirements: "Physical fitness test (PFT), medical examination, and written test",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "Indian Air Force Airmen (Group X - Education Instructor Trade)",
        agelimit: "20-25 years",
        eligibility: "Graduate-level education (but 12th pass required as a base qualification for this exam)",
        AdditionalRequirements: "Physical fitness test (PFT), medical exam, and interview process",
        Nationality: "The candidate must be a citizen of India",
        

      },
      {
        exam: "Indian Air Force Airmen (Group Y - Accounts Assistant)",
        agelimit: "17-21 years",
        eligibility: "12th pass in Commerce with 50% marks in aggregate and 50% marks in English",
        AdditionalRequirements: "Physical fitness test (PFT), medical examination, and written test",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "AFCAT (Air Force Common Admission Test) - Flying Branch",
        agelimit: "20-24 years",
        eligibility: "Graduation (3 years) in any discipline with at least 60% marks and Physics and Maths at 10+2 level OR BE/B.Tech (4 years) with 60% marks",
        AdditionalRequirements: "AFCAT written test, physical fitness test, medical examination, and SSB interview",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "AFCAT - Ground Duty (Technical Branch)",
        agelimit: "20-26 years",
        Eligibility: "BE/B.Tech degree in relevant fields like Aeronautical, Mechanical, or Electronics Engineering with 60% marks",
        AdditionalRequirements: "AFCAT written test, physical fitness test, medical examination, and SSB interview",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "AFCAT - Ground Duty (Non-Technical Branch)",
        agelimit: "20-26 years",
        eligibility: "Graduation (3 years) in any discipline with at least 60% marks, or a Post-Graduate degree (for certain roles)",
        AdditionalRequirements: "AFCAT written test, physical fitness test, medical examination, and SSB interview",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "NCC Special Entry - Flying Branch",
        agelimit: "20-24 years",
        eligibility: "Graduation (3 years) in any discipline with at least 60% marks and Physics and Maths at 10+2 level OR BE/B.Tech (4 years) with 60% marks and NCC Air Wing 'C' Certificate",
        AdditionalRequirements: "No written test required; SSB interview, medical exam, and physical fitness test",
        Nationality: "The candidate must be a citizen of India",
      },
      {
        exam: "Meteorology Branch (Non-AFCAT Entry)",
        agelimit: "20-26 years",
        eligibility: "Post-Graduation in any Science stream / Mathematics / Statistics / Geography / Computer Applications with at least 50% marks",
        AdditionalRequirements: "Direct SSB interview, medical examination, and physical fitness test",
        Nationality: "The candidate must be a citizen of India",
      },
     
];